### ISSUE TITLE
Incorrect OS Names

### ISSUE THREAD

**Issue by aaronparker** [MicrosoftDocs/fslogix-docs#1]
The page currently reads:

> Desktop - Windows 2007
> Server - 2008 R2

It should read:

> Desktop - Windows 7
> Server - Windows Server 2008 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview#feedback)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, Thanks!

**Comment by MrRitt** [comment]
Are Windows 7 and 2008 R2 still supported? Or, are they end of life?
Curious if the solution will work with Windows 7 / 2008 R2 accessing the various storage options available there.

**Comment by DougCoombs** [comment]
FSLogix is supported, but only in scenarios where the OS is still supported.

Thanks!

Doug
