### ISSUE TITLE
Program Files variable incorrectly has space included.

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/fslogix-docs#102]
Variable for Program Files incorrectly has a space in it, in the following

Copy robocopy.exe to the %Program Files%\FSLogix\Apps folder as frxrobocopy.exe
Add an exclusion for the anti-virus product for %Program Files%\FSLogix\Apps\frxrobocopy.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210b2987-c214-abe0-d248-8e851b4ba043
* Version Independent ID: 09e4be89-9877-af60-9ab5-a9a4defe11fd
* Content: [FSLogix installed components and functions - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-installed-components-functions-reference)
* Content Source: [fslogix-docs/fslogix-installed-components-functions-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-installed-components-functions-reference.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
Updated - changes will be live by EOD
