### ISSUE TITLE
Is Server 2022 supported?

### ISSUE THREAD

**Issue by snorma01** [MicrosoftDocs/fslogix-docs#103]
Is the latest version of FSLogix supported in Server 2022? If not, is an updated FSLogix release that adds support expected soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by SteveD-MSFT** [comment]
Yes, Server 2022 is supported.
