### ISSUE TITLE
"Microsoft FSLogix for the enterprise" link is broken

### ISSUE THREAD

**Issue by dcjacob1999** [MicrosoftDocs/fslogix-docs#104]
![image](https://user-images.githubusercontent.com/85578360/138901914-bd6eac55-4c48-4c94-9db9-7621c9795e19.png)

![image](https://user-images.githubusercontent.com/85578360/138901999-aad26b9c-f8e8-4a1c-8de5-1b024770383d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by SteveD-MSFT** [comment]
Thanks! This will be resolved in the next published update.
