### ISSUE TITLE
翻訳がおかしい。

### ISSUE THREAD

**Issue by sasatotokoko** [MicrosoftDocs/fslogix-docs#105]
英語版の文章と日本語版の文章で異なっています。

英語版：VHDLocations may be replaced by CCDLocations when using Cloud Cache

日本語版：クラウド キャッシュを使用する場合、VHDLocations は、VHDLocations によって置 き換えられる可能性があります

日本語版では、CCDLocations の部分が VHDLocations になっており、おかしな文章になっています。

正しい日本語版は
クラウド キャッシュを使用する場合、VHDLocations は、CCDLocations によって置 き換えられる可能性があります
になると思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 734788a0-bfe6-1916-7300-1fea39127604
* Version Independent ID: 254293a7-3f94-d1b8-50f4-4eda0f20552d
* Content: [プロファイル コンテナーの構成のチュートリアル - FSLogix](https://docs.microsoft.com/ja-jp/fslogix/configure-profile-container-tutorial#feedback)
* Content Source: [fslogix-docs/configure-profile-container-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr.ja-JP/blob/live/fslogix-docs/configure-profile-container-tutorial.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
This is addressed in a future documentation update coming later this month.
