### ISSUE TITLE
Get notified about FSLogix updates

### ISSUE THREAD

**Issue by JoeRainero** [MicrosoftDocs/fslogix-docs#106]
Hello,

How do I get notifications about updates to FSLogix?  Because the software will not update itself automatically we need to know whenever an update is available.  Please advise.

Thanks,
Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 359cd9ac-6732-1b85-b411-bbdce4570e83
* Version Independent ID: 3f57cfd0-d7c3-b507-3ecf-a776817da138
* Content: [FSLogix Release Notes - FSLogix](https://docs.microsoft.com/en-us/fslogix/whats-new)
* Content Source: [fslogix-docs/whats-new.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/whats-new.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by SteveD-MSFT** [comment]
We post updates to the FSLogix documentation and announce them on the AVD Tech Community: https://techcommunity.microsoft.com/t5/azure-virtual-desktop
