### ISSUE TITLE
How to exclude registry key from FSLogix

### ISSUE THREAD

**Issue by hishiura** [MicrosoftDocs/fslogix-docs#108]
[Enter feedback here]

I would like to exclude some registry key from FSLogix.
Like this "HKEY_CURRENT_USER\Software\xxxx"
What do I  need to write at redirections.xml?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960d3cdb-4c5a-7c10-a78e-127b1216a547
* Version Independent ID: a1bf2ff6-41a6-e840-676e-0eb4b9feed72
* Content: [Profile Container content - FSLogix](https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt)
* Content Source: [fslogix-docs/manage-profile-content-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/manage-profile-content-cncpt.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
Excluding registry keys isn't supported.
