### ISSUE TITLE
Add Exclusion for OfficeFileCache

### ISSUE THREAD

**Issue by miked1313** [MicrosoftDocs/fslogix-docs#109]
Since IncludeOfficeFileCache defaults to 1 enabled for the Office Container, please add the recommended profile management exclusion for:

Office File Cache
If you have the following setting IncludeOfficeFileCache=1 then you need to exclude the following directory (and sub-dirs):
\Users\<username>\AppData\Local\Microsoft\Office\16.0\OfficeFileCache

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/bb7506f2-1904-406b-b4e3-ea2b9d3c6211/office-365-container-exclusions?forum=FSLogix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2abb4dc-ab6a-16ef-5f4c-75e841c7aa74
* Version Independent ID: 1a4ce9f8-89c0-db9e-a08d-9e63f40766c3
* Content: [Configure Office Container Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-office-container-tutorial)
* Content Source: [fslogix-docs/configure-office-container-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-office-container-tutorial.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by SteveD-MSFT** [comment]
Hi. The OfficeFileCache is now machine specific and cannot be roamed so we are actually removing it from the container and this reg key will also be removed as it won't be necessary. That change will be made in the next release. Public preview will be available before the end of January.

**Comment by miked1313** [comment]
Is there an article/doc on which versions of Microsoft Office or version of 365 apps for Enterprise (ProPlus) has the machine specific OfficeFileCache?  If some supported versions of Microsoft Office still have OfficeFileCache in the user profile, shouldn't FSLogix still support that until those version of Office are no longer supported by Microsoft?
