### ISSUE TITLE
missing how to properly update fslogix section

### ISSUE THREAD

**Issue by walkercz** [MicrosoftDocs/fslogix-docs#111]
Hello,

It would be nice to have a "how to update fslogix" section in fslogix manual

Is it ok to do just a repair fslogix app on running machine or should logoff all users first then uninstall and reinstall the fslogix app? Is restart required and so on. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb001371-1df6-d412-0de5-3c71047a1774
* Version Independent ID: aa2c6d81-169d-55d3-f8f3-33af9b006448
* Content: [Install FSLogix Agent - FSLogix](https://docs.microsoft.com/en-us/fslogix/install-ht)
* Content Source: [fslogix-docs/install-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/install-ht.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by danaelg** [comment]
Same question here

**Comment by msft-jasonparker** [comment]
There is no "update".  FSLogix is ONLY a full install and anytime you install the product, you should reboot the VM.

**Comment by SvenAelterman** [comment]
@msft-jasonparker I am sorry, but that's not a very helpful answer. The question seems to be about existing session hosts that are running FSLogix. When an FSLogix patch or new version is released, what's the right approach to take? I think it's a reasonable request to add that to the docs.

**Comment by stalks** [comment]
> There is no "update". FSLogix is ONLY a full install and anytime you install the product, you should reboot the VM.

Then lets add this to the document then. "You can't update FSLogix, you need to do X, Y, or Z".

**Comment by DeepMalh44** [comment]
@walkercz  @SvenAelterman and @stalks , I have re-opened the above issue again as seems that this #111 issue was closed without any answer.
