### ISSUE TITLE
concurrent setting documentation question

### ISSUE THREAD

**Issue by davisray1983** [MicrosoftDocs/fslogix-docs#112]
[Enter feedback here]

Hello and Good Evening/Morning,

Does anyone know who at MS we can contact to get them to update or address the documentation around FSLogix "concurrent setting for: " Concurrent connections would generally be used in specific environments, such as with a Citrix implementation?”

It was removed and noted here.
ConcurrentUserSessions setting should be removed · Issue #85 · MicrosoftDocs/fslogix-docs (github.com)

It was also removed from the ADMX as well.

However, The Docs still reflect this and it states "Citrix Environments" 
https://docs.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht#concurrent-connections-with-profile-container-and-office-container

It does seem MS might be still giving out advice to set it in the registry as well according to this and maybe be confused as well?
https://docs.microsoft.com/en-us/answers/questions/259305/was-the-34allow-concurrent-users-sessions34-gp-set.html

Where the confusion comes into play is folks are getting it mixed up and confusing it, thinking that is a must for XenApp(Virtual Apps)
What is the real need for it if the following are true below for a Citrix Environment?

1. fSingleSessionPerUser  is applied to RDSH, not Citrix Virtual App (XenApp after 7.6) https://support.citrix.com/article/CTX203046

2. Session sharing would be used here in the Citrix Stack, which allows the same user to open multiple sessions under the same ID for application on that server. All applications launch in the same application session
“Session sharing is the ability of a seamless published application to be executed over the same connection as other seamless applications that are already running on the same server, under an existing Session ID of a user.”
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5945f8f-44c8-f087-9242-a33e3b1314db
* Version Independent ID: 96ff0876-4761-7f23-8916-b16b2226b921
* Content: [Supporting concurrent connections and multiple connections with Profile Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht#concurrent-connections-with-profile-container-and-office-container)
* Content Source: [fslogix-docs/configure-concurrent-multiple-connections-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-concurrent-multiple-connections-ht.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by SteveD-MSFT** [comment]
Thanks for calling this out. No longer supports those registry keys and customers need to leverage the fSingleSessionPerUser key value.
