### ISSUE TITLE
Debug and robocopypath logging fslogix

### ISSUE THREAD

**Issue by extromen13** [MicrosoftDocs/fslogix-docs#113]
Hi,

Is here anyone for who works fslogix robocopy log and debug Level logging? I am trying to set as described here:

https://docs.microsoft.com/en-us/fslogix/logging-diagnostics-reference

But logginglevel and robocopylogpath seems have no effect for me :( Any experience, anyone?

Thanks a lot

**Comment by msft-jasonparker** [comment]
This is addressed in a future documentation update coming later this month.
