### ISSUE TITLE
Allow concurrent user sessions

### ISSUE THREAD

**Issue by mmitchellcit** [MicrosoftDocs/fslogix-docs#114]
This setting (Allow concurrent user sessions) is described in the documentation for Profile Containers and Office Containers, but it is unable to be configured with group policy, even with the latest ADMX/ADML files loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a490a35-0b6c-c2e5-dc10-5f72c7e906b7
* Version Independent ID: bca503d7-f9a6-6e95-7fa9-f5d46b8ac801
* Content: [Use FSLogix Group Policy Template Files - FSLogix](https://docs.microsoft.com/en-us/fslogix/use-group-policy-templates-ht)
* Content Source: [fslogix-docs/use-group-policy-templates-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/use-group-policy-templates-ht.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by MikeStreetz** [comment]
See issue 85, the setting has been removed as it now relies on if FSingleSessionPerUser set to 0 or not. 
[https://github.com/MicrosoftDocs/fslogix-docs/issues/85](url)
I agree that the screenshots should be updated to ones that do not show this setting.

**Comment by msft-jasonparker** [comment]
The FSLogix specific settings are configurable via Group Policy.

Profile Container:
- Computer Config\Policies\Admin Templates\FSLogix\Profile Containers\Profile Type

Office Container:
- Computer Config\Policies\Admin Templates\FSLogix\Office 365 Containers\VHD access type

The other settings:
- fDenyTSConnections
- fSingleSessionPerUser

These are not FSLogix settings, but are required for this to work.
