### ISSUE TITLE
Where's the documentation for the WriteCache value ?

### ISSUE THREAD

**Issue by JonathanPitre** [MicrosoftDocs/fslogix-docs#115]
Where's the documentation for the WriteCache value ?
Can we push the WriteCache value via GPO or it's not supported and must be applied manually to the master image like the CacheDirectory  value?

It's recommended to move these directories when using Citrix MCSIO or Citrix PVS. Please document this properly with more details.
https://github.com/EUCweb/BIS-F/issues/276
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e794b36e-21f9-5545-cd15-a528f34cbc46
* Version Independent ID: ec93ddfb-158f-0305-f615-1776086d34c1
* Content: [FSLogix Cloud Cache configuration reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference)
* Content Source: [fslogix-docs/cloud-cache-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
What setting are you referring to?  There is no write cache setting.
