### ISSUE TITLE
Use FSLogix Group Policy Template Files missing from table of contents

### ISSUE THREAD

**Issue by miked1313** [MicrosoftDocs/fslogix-docs#117]
This is a great page that I do not see listed in the FSLogix table of contents on the left hand side.  I found it by searching Microsoft Docs.  Can you add it to the FSLogix TOC perhaps under How-to Guides or Reference?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a490a35-0b6c-c2e5-dc10-5f72c7e906b7
* Version Independent ID: bca503d7-f9a6-6e95-7fa9-f5d46b8ac801
* Content: [Use FSLogix Group Policy Template Files - FSLogix](https://docs.microsoft.com/en-us/fslogix/use-group-policy-templates-ht)
* Content Source: [fslogix-docs/use-group-policy-templates-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/use-group-policy-templates-ht.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
Great find, we'll update it.
