### ISSUE TITLE
Need to make changes to Profile type Read only

### ISSUE THREAD

**Issue by dk7869p** [MicrosoftDocs/fslogix-docs#118]
Hello MS team, Today I was reading about profile type and came to see that even profile type 2 which is Read only have RW.vhdx created on machine and I believe it creates RO.vhdx.

If you could please correct that will be appreciated. 

And wish me all the best for my Interview at Microsoft :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5945f8f-44c8-f087-9242-a33e3b1314db
* Version Independent ID: 96ff0876-4761-7f23-8916-b16b2226b921
* Content: [Supporting concurrent connections and multiple connections with Profile Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht)
* Content Source: [fslogix-docs/configure-concurrent-multiple-connections-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-concurrent-multiple-connections-ht.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
The page has been updated with new content
