### ISSUE TITLE
Clarification needed | Cloudcache

### ISSUE THREAD

**Issue by TarekNabeel** [MicrosoftDocs/fslogix-docs#119]
Hello,
I need clarification on what is meant by "base product" and "Full product" on the below statement mention on the documentation , also for "SMB" type with base product what is meant by "one remote container mabe specified ? does this mean that is does not support HA? 

" _When setting CCDLocations for a **base product,** Type must be SMB and only and one remote container may be specified. When setting CCDLocations for **full products**, Type may be any supported CCDLocations type, and up to four remote container locations may be specified._"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e794b36e-21f9-5545-cd15-a528f34cbc46
* Version Independent ID: ec93ddfb-158f-0305-f615-1776086d34c1
* Content: [FSLogix Cloud Cache configuration reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference)
* Content Source: [fslogix-docs/cloud-cache-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
The page has been updated.
