### ISSUE TITLE
Clarify (detail?) relationship between OutlookCachedMode and NoOST

### ISSUE THREAD

**Issue by joshtbernstein** [MicrosoftDocs/fslogix-docs#12]
I'm not sure where [this](https://docs.microsoft.com/en-us/fslogix/20170529/Office+365+Configuration+Settings) KB was moved to, but I wanted to offer up some thoughts.

Clarifying that that the user still needs to enable Outlook Cached Mode (either through GPO or manually) would be helpful as this wasn't clear to me. It sounded as if it should be disabled and FSLogix would enable it. Instead cached mode should be enabled, then setting NoOST=2 in the registry disables it and finally when FSLogix sets NoOST=0 (after successful VHD(X) attach) it's enabled at a per user level.

It's also worth mentioning that even though NoOST needs to be set under HKEY_LOCAL_MACHINE, FSLogix will still override this at a user level. I was expecting to see NoOST=0 under HKEY_CURRENT_USER.

Cassondra from support is pretty good at explaining this and would probably be a good resources to update this part of the documentation.

**Comment by DougCoombs** [comment]
There is now a note in the reference document for OutlookCacheMode indicating that the comment re override at user level.

**Comment by joshtbernstein** [comment]
@DougCoombs Do you have a link to that change? Thank you.
