### ISSUE TITLE
PLease provide download links for previous versions

### ISSUE THREAD

**Issue by AzureAzim** [MicrosoftDocs/fslogix-docs#120]
I have a customer asking for the links for previous releases be available so that they can download FSL legacy versions and test new releases prior to rolling out to their customers populations. Making the legacy downloads available on this page will be very helpful to customers where changes to the version may cause problems for them, this will allow them to move with confidence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef9db9f-d2a5-e4be-57cc-265310659c02
* Version Independent ID: baa86801-4ace-567b-a0e7-6d4ea072df5f
* Content: [Cloud Cache for resiliency and availability - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-resiliency-availability-cncpt)
* Content Source: [fslogix-docs/cloud-cache-resiliency-availability-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-resiliency-availability-cncpt.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
There are 2 ways to download previous versions:
1. [Release Notes page](https://docs.microsoft.com/en-us/fslogix/whats-new)
2. [Search Download Center](https://www.microsoft.com/en-us/search/explore?q=download+fslogix)

The FSLogix team only allows the current and previous full feature releases available for public download.
