### ISSUE TITLE
Referenced Page is not found 

### ISSUE THREAD

**Issue by kumarallamraju** [MicrosoftDocs/fslogix-docs#122]
[Enter feedback here]
Error Codes
Usually when an FSLogix component is not working, Error will be set. When it is set, it corresponds to a standard [Windows Error Code](https://msdn.microsoft.com/library/windows/desktop/ms681382(v=vs.85).aspx).

This page is not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ddcd3b5-8767-395d-47f1-d411d699da9c
* Version Independent ID: b1449d8b-86ee-48dd-ac30-44a15041af1b
* Content: [FSLogix error code reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-error-codes-reference)
* Content Source: [fslogix-docs/fslogix-error-codes-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-error-codes-reference.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
Page resolve correctly.
