### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by joebrug** [MicrosoftDocs/fslogix-docs#124]
"The configuration of Office Container is accomplished through registry settings and user groups. Registry settings may be managed manually, with [GPOs](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-a-group-policy-object), or using alternate preferred methods. Configuration settings for Profile Container are set in HKLM\SOFTWARE\Policies\FSLogix\ODFC."

I believe the last line should say "Configuration settings for **OFFICE** Container are set in HKLM\SOFTWARE\Policies\FSLogix\ODFC"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2abb4dc-ab6a-16ef-5f4c-75e841c7aa74
* Version Independent ID: 1a4ce9f8-89c0-db9e-a08d-9e63f40766c3
* Content: [Configure Office Container Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-office-container-tutorial)
* Content Source: [fslogix-docs/configure-office-container-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-office-container-tutorial.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
Will be addressed in a future doc update later this month.
