### ISSUE TITLE
Typo in the page

### ISSUE THREAD

**Issue by danielharkerdp** [MicrosoftDocs/fslogix-docs#13]
"that apply t0 specific" - I assume that should be an O? for some reason I don't have the usual options modify the page and submit a pull request

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3acf8ad-adcb-7d9e-6d73-0a7d964553c7
* Version Independent ID: 1f4b517e-6a90-283d-af81-5933ec7e1f65
* Content: [Configure Profile Container and Office Container for per user or per group - FSLogix](https://docs.microsoft.com/en-gb/fslogix/configure-per-user-per-group-ht)
* Content Source: [fslogix-docs/configure-per-user-per-group-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-per-user-per-group-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, thank you!
