### ISSUE TITLE
You did not mentioned how to add for Azure AD Groups, 

### ISSUE THREAD

**Issue by PaddyMaddy** [MicrosoftDocs/fslogix-docs#130]
[Enter feedback here]

You did not mentioned how to add for Azure AD Groups, if the Sessionhost is from Azure AD joined devices
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abbd66f3-5e06-8f21-3545-7c71a72400b4
* Version Independent ID: c3ea68be-b26d-7e9b-61d2-c4c3c62e4232
* Content: [Application Masking users and groups - FSLogix](https://learn.microsoft.com/en-us/fslogix/application-masking-users-groups-ht)
* Content Source: [fslogix-docs/application-masking-users-groups-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/application-masking-users-groups-ht.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Azure AD cloud only users is not supported. Users must have hybrid identity and line of sight to domain controllers.
