### ISSUE TITLE
Document ExcludeCommonFolders values in Redirections.xml

### ISSUE THREAD

**Issue by msft-rasgun** [MicrosoftDocs/fslogix-docs#131]
Looking at the Redirections.xml documentation, some out-dated blogs seem to know the following values are valid for ExcludeCommonFolders:
1 = Contacts folder
2 = Desktop folder
4 = Documents folder
8 = Downloads folder
16 = Links folder
32 = Music and Podcasts folders
64 = Pictures and Videos folders
128 = Folders involved in Low Integrity Level processes like AppData\LocalLow

It's also noted on other blogs that the ExcludeCommonFolders value no longer have any effect, however in my testing, at least Value=8 does indeed exclude the Downloads folder. I didn't test any other values/combinations of values.

Ask:
If still supported/valid, please document possible values for ExcludeCommonFolders. 
If no longer supported/valid, please document that as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 960d3cdb-4c5a-7c10-a78e-127b1216a547
* Version Independent ID: a1bf2ff6-41a6-e840-676e-0eb4b9feed72
* Content: [Profile Container content - FSLogix](https://learn.microsoft.com/en-us/fslogix/manage-profile-content-cncpt)
* Content Source: [fslogix-docs/manage-profile-content-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/manage-profile-content-cncpt.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
We are addressing this in a future documentation update later this month.
