### ISSUE TITLE
Concurrent User Sessions No Longer Allowed?

### ISSUE THREAD

**Issue by bradmoutoux** [MicrosoftDocs/fslogix-docs#132]
I am using FSLogix 2.9.8361 with Citrix VAD 2212 and we are using profile containers to store user information along with their M365 settings.  What I am running into is, if I ever need to check multiple session hosts for hung sessions or to do any maintenance, I cannot log into more than 1 session host at a time.  I have found that the setting that allowed for this was removed.  So what replaces it? There are use cases for this setting.  However, what I really need is to be able to RDP into the Windows Server and not be limited to logging into one at a time.  How would I accomplish that?  We do not use Virtual Desktops and only use Virtual Apps.

**Comment by msft-jasonparker** [comment]
This feature was not removed and still works. What indicates that the feature or setting was removed?

https://learn.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht

**Comment by bradmoutoux** [comment]
We got it figured out.  It was a couple months ago, so I can't remember if it was just in a different place or what.
