### ISSUE TITLE
GetSupportedSizes hyperlink results in a 404

### ISSUE THREAD

**Issue by rtebrake** [MicrosoftDocs/fslogix-docs#133]
There are 4 links on this page regarding GetSupportedSize that link [here](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/stormgmt/msft-partition-getsupportedsizes) but this results in a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc16df73-8a97-7ee1-65fa-f6430ff9dd30
* Version Independent ID: dc16df73-8a97-7ee1-65fa-f6430ff9dd30
* Content: [VHD Disk Compaction - FSLogix](https://learn.microsoft.com/en-us/fslogix/concepts-vhd-disk-compaction)
* Content Source: [fslogix-docs/concepts-vhd-disk-compaction.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/concepts-vhd-disk-compaction.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
fixed
