### ISSUE TITLE
FSLogix 2210 slows down logoff, stuck user logout process

### ISSUE THREAD

**Issue by vargasol** [MicrosoftDocs/fslogix-docs#134]
Hi,

It is regarding FSLogix version 2210. 

In case of two of our users have an issue, that when this version FSLogix 2210 installed, the logon process takes approx. 20 minutes. After the user finishes his/her work, the logoff never finishes and the AVD host **must be deallocated**, because the session cannot be signed off neither remotely nor from the host itself. It stucked completely and keeps profile file open. The user cannot log back anymore.

When I replace the FSLogix with version 2201, the login procedure took only 2 minutes, and the logoff process finished with success.

Thanks!

Gabor Varga

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bcde7d28-7506-30a6-eaca-118a2497e496
* Version Independent ID: bc463792-97c2-9b3e-3af9-865bfe06c00b
* Content: [Troubleshooting FSLogix products - FSLogix](https://learn.microsoft.com/en-us/fslogix/fslogix-trouble-shooting-ht)
* Content Source: [fslogix-docs/fslogix-trouble-shooting-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-trouble-shooting-ht.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Addressed in 2210 hotfix 1
