### ISSUE TITLE
Synchronous vs. asynchronous 

### ISSUE THREAD

**Issue by tsrob50** [MicrosoftDocs/fslogix-docs#135]
I think the line "This is a synchronous process, limited by the performance of the various system components such as client, network and storage." should be "an asynchronous process.."  Synchronous would indicate a write is acknowledged by the cloud cache provider before it's acknowledged by the cache.  Asynchronous is near realtime. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef9db9f-d2a5-e4be-57cc-265310659c02
* Version Independent ID: baa86801-4ace-567b-a0e7-6d4ea072df5f
* Content: [Cloud Cache for resiliency and availability - FSLogix](https://learn.microsoft.com/en-us/fslogix/cloud-cache-resiliency-availability-cncpt)
* Content Source: [fslogix-docs/cloud-cache-resiliency-availability-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-resiliency-availability-cncpt.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
This will be addressed in a future doc update later this month.
