### ISSUE TITLE
Local groups not saved

### ISSUE THREAD

**Issue by Marshmllw** [MicrosoftDocs/fslogix-docs#136]
I recently noticed that the local group settings we make for the inclusion or exclusion of users from the FSLogix processes are being reset back to default after a reboot of the servers.

It does not seem to be an known issue as reported on the FSLogix articles
https://learn.microsoft.com/en-us/fslogix/troubleshooting-known-issues

I was wondering if others have noticed this as well, and if so, what they did to fix it.

**Comment by msft-jasonparker** [comment]
FSLogix doesn't control local groups or their members. I would check that some other process or policy isn't removing those members.
