### ISSUE TITLE
Request to include details on NTFS root permissions for Azure File share use with fslogix 

### ISSUE THREAD

**Issue by alozzy** [MicrosoftDocs/fslogix-docs#137]
Sure would be helpful if Azure File specific details were provided here, so that one can mount a drive to the Azure File share via the storage key and then edit the root NTFS permissions to match what one would do on a traditional file server.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d718ea32-d8b7-9771-02eb-ca17ddfac068
* Version Independent ID: 8a030e13-4a6e-d674-1ef2-b6117c207203
* Content: [Storage Permissions for Profile Container and Office Container - FSLogix](https://learn.microsoft.com/en-us/fslogix/fslogix-storage-config-ht)
* Content Source: [fslogix-docs/fslogix-storage-config-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-storage-config-ht.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
This is addressed in a future documentation update coming later this month.
