### ISSUE TITLE
Azure AD Authentication Issue Needs Clarification

### ISSUE THREAD

**Issue by jamesaepp** [MicrosoftDocs/fslogix-docs#138]
The article states the below:

---
Starting in FSLogix 2210 (2.9.8361.52326) and later versions, all content stored in following locations is no longer roamed as part of the user profile.

    %USERPROFILE%\AppData\Local\Packages\Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy
    %USERPROFILE%\AppData\Local\Packages\Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy
    %USERPROFILE%\AppData\Local\Microsoft\TokenBroker
---

What is unclear is if this itself is a true **bug** which is going to be resolved in future releases or if this is a new **feature** which needs to be worked around by administrators going forward for all new versions. *If* the latter, the article should link to further documentation or recommendations on how to work around the problem. Because on the surface it makes no sense why FSLogix would break another component of the operating system.

If it's a security precaution by the developers of FSLogix, then at least give administrators a GPO to override this "feature".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21faf98c-ef78-83b6-2eea-c866f174311c
* Version Independent ID: 21faf98c-ef78-83b6-2eea-c866f174311c
* Content: [Known Issues - FSLogix](https://learn.microsoft.com/en-us/fslogix/troubleshooting-known-issues)
* Content Source: [fslogix-docs/troubleshooting-known-issues.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/troubleshooting-known-issues.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
We've updated this known issue and released a hotfix.
