### ISSUE TITLE
Link is wrong for GPO

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/fslogix-docs#14]
Link is wrong for GPO Shortcut. Currently pointing to:
https://docs.microsoft.com/windows/security/threat-protection/windows-firewall/create-a-group-policy-object

Is this supposed to be a link covering specific details on the FSLOgix ADMX?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 734788a0-bfe6-1916-7300-1fea39127604
* Version Independent ID: 254293a7-3f94-d1b8-50f4-4eda0f20552d
* Content: [Configure Profile Container Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-profile-container-tutorial#feedback)
* Content Source: [fslogix-docs/configure-profile-container-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-profile-container-tutorial.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
incorrect link removed.
