### ISSUE TITLE
Missing format description for AppxPackages.xml in feature / reg key installappxpackages

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/fslogix-docs#140]
When configuring the feature "installappxpackages" the registry key will refer to the file %APPDATALOCAL%\FSLogix\AppxPackages.xml
But literally nowhere on earth including Google the required structure for this file is documented.

Please add also a description about the required structure. Or if a stub is generated when enabling it then even this information.
We need to know how this can be configured in detail! Especially as we have currently Appx apps just disappearing from user profiles where a re-registering is required often.

https://learn.microsoft.com/en-us/fslogix/reference-configuration-settings?tabs=profiles#installappxpackages

Thank you for fixing this documentation bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01eecaa9-373c-0b07-ea97-4f818ff3a117
* Version Independent ID: 01eecaa9-373c-0b07-ea97-4f818ff3a117
* Content: [Configuration Settings - FSLogix](https://learn.microsoft.com/en-us/fslogix/reference-configuration-settings?tabs=profiles)
* Content Source: [fslogix-docs/reference-configuration-settings.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/reference-configuration-settings.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
The AppxPackages.xml file is not meant to be edited or modified. Editing this file may cause unexpected results and the file will be overwritten by the FSLogix service.
