### ISSUE TITLE
Wrong information in Prerequisites for FSLogix search roaming.

### ISSUE THREAD

**Issue by jasonyusz** [MicrosoftDocs/fslogix-docs#141]
FSLogix 2201 and newer do not allow FSLogix Search roaming on versions of Windows that natively provide per-user search indexes. Per-user search indexes are natively supported by Windows Server 2019 version 1809 and newer, as well as all versions of Windows 10 multi-session and Windows 11 multi-session.

Below information for Prerequisites needs to update:

**Supported Server Operating Systems: _Windows Server 2019 version 1809 or newer_
Supported Desktop Operating Systems: _Windows 10 Enterprise Multi-session or Windows 11 Enterprise Multi-session_**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0372ee4-56a3-5b1c-e5df-1d5890c15d3c
* Version Independent ID: b7f96ccb-1bc2-251b-8b7c-4ff20d405b0b
* Content: [Roam the windows search database with Profile Container - FSLogix](https://learn.microsoft.com/en-us/fslogix/configure-search-roaming-ht?source=docs)
* Content Source: [fslogix-docs/configure-search-roaming-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-search-roaming-ht.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
fixed
