### ISSUE TITLE
Anti-Virus Exclusions

### ISSUE THREAD

**Issue by AshleyHow** [MicrosoftDocs/fslogix-docs#142]
The published exclusions are different from https://learn.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix

These new ones are missing previously advised process exclusions, .sys files, plus there is an extra "\\*" across some exclusions, along with some additional lock and metadata files now.

What ones are correct here and at what point did we need to change them to include these lock and metadata files?

**Comment by msft-jasonparker** [comment]
The exclusions in the FSLogix docs are correct. Other docs are getting updated by other teams.
