### ISSUE TITLE
Typo in latest version link

### ISSUE THREAD

**Issue by danielmarker** [MicrosoftDocs/fslogix-docs#143]
Link in 2nd para to "latest version" has a typo

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Version Independent ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Content: [FSLogix Release Notes - FSLogix](https://learn.microsoft.com/en-us/fslogix/overview-release-notes)
* Content Source: [fslogix-docs/overview-release-notes.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-release-notes.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
fixed
