### ISSUE TITLE
"Latest version" link is broken

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/fslogix-docs#144]
Goes to goes to https://aka.ms/latest-version which doesn't give FSlogix downloads as it looks too generic for that

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea880afe-8f06-c0e4-1118-ae3286e2f0d0
* Version Independent ID: ea880afe-8f06-c0e4-1118-ae3286e2f0d0
* Content: [Prerequisites for FSLogix - FSLogix](https://learn.microsoft.com/en-gb/fslogix/overview-prerequisites)
* Content Source: [fslogix-docs/overview-prerequisites.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-prerequisites.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
fixed
