### ISSUE TITLE
local cache to central storage

### ISSUE THREAD

**Issue by rvanderkruk** [MicrosoftDocs/fslogix-docs#146]
Please describe in more detail how the local cache is used; at what interval or trigger is the data in the local cached sent to the remote storage providers? How large should the local cache generally be? a few kb, MB, GB?

thanks
Roland van der Kruk

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 658bf8f2-3a48-9236-4d97-937fa898c99e
* Version Independent ID: 658bf8f2-3a48-9236-4d97-937fa898c99e
* Content: [Cloud Cache Overview - FSLogix](https://learn.microsoft.com/en-us/fslogix/concepts-fslogix-cloud-cache)
* Content Source: [fslogix-docs/concepts-fslogix-cloud-cache.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/concepts-fslogix-cloud-cache.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
We intentionally do not document how and when the data is written to the remote storage providers. The local cache is representative of the full size of the users profile.  There is no "right" size as each customers requirements are different and their workloads are different.

If provided, how would the information you are seeking benefit you or others?

**Comment by rvanderkruk** [comment]
Jason,

it is just the technical background of how it exactly works with the cache. If network connection to the vhdx is lost maybe the cache will fill up until full size, but what is the behavior when a full speed network connection is available ? I would reckon that the cache then is not supposed to be very large.

It is to give people an understanding of what to expect in which situation, at initial deployment but also during regular operations.

Hope that helps clarity my need for more information.


Regards

Roland van der Kruk
Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by msft-jasonparker** [comment]
Thanks for the feedback, I've added new information to the Cloud Cache overview page specifically for remote storage providers. I'm hoping this fills the gap you feel is missing.
