### ISSUE TITLE
Single Session Operating System

### ISSUE THREAD

**Issue by rupali-22** [MicrosoftDocs/fslogix-docs#148]
Hello Jason,

Thanks for your response.

Just to confirm, search is configured on Windows 10 Single session operating systems as well and no action is required from the setup perspective?

I found this difference when I setup FSLogix in multisession os and single session os - Windows 10 20H2:
![Windows Search](https://user-images.githubusercontent.com/130623566/232662940-f183b833-223a-4792-88c5-a5a9218499fa.png)

Windows Search

**Comment by msft-jasonparker** [comment]
FSLogix Search roaming is only applicable to Windows 10/11 single session (Enterprise SKU) or Windows server prior to 2019 1809.  The logs in your screenshot is accurate.

**Comment by rupali-22** [comment]
Thanks Jason 😊

Appreciate the explanation.

Regards,

Rupali Borkar
Support Engineer
Windows Commercial – User Experience
• +61 (3) 9320 4398 • ***@***.******@***.***>
Working hours: M-F 9:00am – 5:30pm AEDT
***@***.***
