### ISSUE TITLE
SizeInMBs setting

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/fslogix-docs#15]
The name of the setting is "SizeInMBs", but the example says for a 30GB drive you should use the number 3000.

If the example is right, we should be multiplying GBs times 100, not 1,000. Is this example correct, or should it really be 30000?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978fd40e-7442-8668-fc98-41fe72488264
* Version Independent ID: 3aaec39c-5ea0-fedc-04ea-e3bd4d7784ff
* Content: [Office Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/office-container-configuration-reference#feedback)
* Content Source: [fslogix-docs/office-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/office-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by MaranVerweij** [comment]
Is the term 'Profile container' being used intermittently where 'Office container' is the correct term? For example:

"Type DWORD
Default Value 0
Data values and use 0: Office Containers disabled. 1: Profile Containers enabled."

It seems to me that both values should read Office Containers. Please verify, I suspect other references incorrectly cite 'Profile Containers' considering this article covers Office Containers.

**Comment by DougCoombs** [comment]
This is corrected, Thank you!

**Comment by BakkerJan** [comment]
There is still a typo here. Description says: Default: 3000=30GB
That should be 30000=30GB
No, wait, this should be 30*1024=30720MB=30GB..... Just saying :)
