### ISSUE TITLE
Cloud Cache Local Cache Sizing Recommendations?

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/fslogix-docs#152]
Wondering if there are any Cloud Cache local cache sizing recommendations?

I've looked in our environment and the local cache can grow to a couple GB. Not a whole lot, but want to ensure we are being optimal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 658bf8f2-3a48-9236-4d97-937fa898c99e
* Version Independent ID: 658bf8f2-3a48-9236-4d97-937fa898c99e
* Content: [Cloud Cache Overview - FSLogix](https://learn.microsoft.com/en-us/fslogix/concepts-fslogix-cloud-cache#hydrate)
* Content Source: [fslogix-docs/concepts-fslogix-cloud-cache.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/concepts-fslogix-cloud-cache.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
We stay aware from specific guidance as environments and profiles can vary greatly and recommendations in our docs getting taken verbatim sometimes which puts us in a bad position.

Things to consider:

1. Concurrent users per VM: 2 per VM vs 30 per VM will have a significant impact on your local cache and storage needs.
2. Container size: 10GB containers vs 80GB containers will have a significant impact on your local cache and storage needs.

Use common sense and know that a user has the potential to create as much data as their profile size will allow. I would use some math around average profile size and max profile size multiplied by concurrent users per VM.

Does that help or how else could this be helpful in our docs?

**Comment by FMCUSystemAdmins** [comment]
Thank you, this aligns with other configurations we've made. Everything is running smoothly!
