### ISSUE TITLE
Viewpoint and what happenend to the old AV exclusion advise

### ISSUE THREAD

**Issue by GertD27** [MicrosoftDocs/fslogix-docs#154]
How to interpret the advice here? Viewpoint - storage like a file server or Client like a VDI. Where do I need to exclude this on AV: Client, Storage or both. 

Previous advise on https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#antivirus-exclusions included files and folders. Reference is gone but is unclear of the new advice replaces the old advice. 
**OLD recomendation:**
Exclude files:
•	%ProgramFiles%\FSLogix\Apps\frxdrv.sys
•	%ProgramFiles%\FSLogix\Apps\frxdrvvt.sys
•	%ProgramFiles%\FSLogix\Apps\frxccd.sys
•	%TEMP%\*.VHDX
•	%Windir%\TEMP\*.VHDX
•	[\\storageaccount.file.core.windows.net\share\*.VHDX](file://storageaccount.file.core.windows.net/share/*.VHDX) 

Exclude processes:
•	%ProgramFiles%\FSLogix\Apps\frxccd.exe
•	%ProgramFiles%\FSLogix\Apps\frxccds.exe
•	%ProgramFiles%\FSLogix\Apps\frxsvc.exe

Is this no longer valid? If so please mention it as many fslogix implementations will be brownfield. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea880afe-8f06-c0e4-1118-ae3286e2f0d0
* Version Independent ID: ea880afe-8f06-c0e4-1118-ae3286e2f0d0
* Content: [Prerequisites for FSLogix - FSLogix](https://learn.microsoft.com/en-us/fslogix/overview-prerequisites#configure-antivirus-file-and-folder-exclusions)
* Content Source: [fslogix-docs/overview-prerequisites.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-prerequisites.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Sorry this information was outdated and the when we retired the article we redirected it to the most appropriate location which doesn't have the exclusions.

You can find them here: https://learn.microsoft.com/en-us/fslogix/overview-prerequisites#configure-antivirus-file-and-folder-exclusions

I'll add a link to the config example page for others who get redirected.
