### ISSUE TITLE
FSLogix Feedback on RoamIdentity

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/fslogix-docs#155]
Hey Team!  I think it would be very helpful to have more _information_ about the purpose of the RoamIdentity setting in relation to Domain Joined only devices and using the latest version of FSLogix.  We discovered that while using the latest FSLogix version while on a Domain Joined device, users would be required to log back into their M365 apps each time they started a new session within AVD.  We discovered we had to enable **RoamIdentity** to resolve this issue.  I think this setting needs to be broadly advertised for customers in that scenario and probably provided on some of the other FSLogix broad documentation as a reference.  Hope this helps!

Example of other Docs that could use this explanation:
- [FSLogix - Configuration Examples](https://learn.microsoft.com/en-us/fslogix/concepts-configuration-examples)
- [FSLogix - FAQ](https://learn.microsoft.com/en-us/fslogix/overview-faq)
- [FSLogix - Configure Profile Containers](https://learn.microsoft.com/en-us/fslogix/tutorial-configure-profile-containers)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01eecaa9-373c-0b07-ea97-4f818ff3a117
* Version Independent ID: 01eecaa9-373c-0b07-ea97-4f818ff3a117
* Content: [Configuration Settings - FSLogix](https://learn.microsoft.com/en-us/fslogix/reference-configuration-settings?tabs=profiles)
* Content Source: [fslogix-docs/reference-configuration-settings.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/reference-configuration-settings.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
What would be your suggestion? We have this article as the known issue: https://learn.microsoft.com/en-us/fslogix/troubleshooting-known-issues#azure-ad-authentication-for-applications

**Comment by brmcmill** [comment]
I don't think users who have to sign into their apps at every sign-in is an optimal user experience.  Providing details on how to overcome that with this setting would help for those specific Domain Joined scenarios.  Entra ID joined is ideally the solution, but not every customer can move their AVD environments to that scenario until later.

**Comment by msft-jasonparker** [comment]
The scenarios in which a customer must use this setting are unknown to our team and we've not been able to reproduce it on our side. Customer who enable this setting are urged to open a support case to understand why their Windows token created during sign-in isn't being used by M365 applications.

Once we have a solid understanding as to what scenarios this applies to, we will add it to our docs.
