### ISSUE TITLE
RoamIdentity DWROD with Default Value: 0 will not exist by default and admins do not need to create it.

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/fslogix-docs#157]
RoamIdentity DWROD, in fact, doesn’t need to be created with Default Value: 0 (and will not exist by default). It would be good to create clarification so admins aren't trying to create this with the noted value because they think it missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01eecaa9-373c-0b07-ea97-4f818ff3a117
* Version Independent ID: 01eecaa9-373c-0b07-ea97-4f818ff3a117
* Content: [Configuration Settings - FSLogix](https://learn.microsoft.com/en-us/fslogix/reference-configuration-settings?tabs=profiles#roamidentity)
* Content Source: [fslogix-docs/reference-configuration-settings.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/reference-configuration-settings.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
I don't think its necessary to add this to only this setting as we have MANY default settings which don't require admins to create.  Do you think we should have a high level note for all the settings?

**Comment by jerryabo** [comment]
I do think so. I've been around a long time and didn't know that. It took an EM noting that for me to understand it to be the case.

**Comment by jerryabo** [comment]
Updated Default settings

After [installing](https://learn.microsoft.com/en-us/fslogix/how-to-install-fslogix) FSLogix, the installer will create a base set of registry keys and values which provides the framework for adding configuration settings. FSLogix doesn't create ANY configuration setting value names as part of the installation. Any configuration setting listed on this page which has a 'Default value' doesn't need to be created or configured as FSLogix will automatically use the default value as listed.
