### ISSUE TITLE
FSLogixAppsRuleEditor in AAD only environment

### ISSUE THREAD

**Issue by osuperfly68** [MicrosoftDocs/fslogix-docs#158]
Will it be possible to use the Rule Editor in an (AVD) AAD only environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a96dd836-c324-3e58-74de-4fcdedc267bb
* Version Independent ID: a96dd836-c324-3e58-74de-4fcdedc267bb
* Content: [FSLogix Apps RuleEditor and Rule Sets- FSLogix - FSLogix](https://learn.microsoft.com/en-us/fslogix/concepts-fslogix-apps-rule-editor-rule-sets)
* Content Source: [fslogix-docs/concepts-fslogix-apps-rule-editor-rule-sets.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/concepts-fslogix-apps-rule-editor-rule-sets.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
No.

https://learn.microsoft.com/en-us/fslogix/overview-faq#can-i-use-fslogix-application-rule-sets-with-azure-ad-and-cloud-only-identities
