### ISSUE TITLE
Assignment order figure 2 issue.

### ISSUE THREAD

**Issue by jasonyusz** [MicrosoftDocs/fslogix-docs#159]
[Enter feedback here]

Regarding the rule set assignment order, this figure definitely wrong, as according to the figure, "Everyone" group does not apply the rule set, so the result should be the rule set is applied to no one:

<img width="443" alt="image" src="https://github.com/MicrosoftDocs/fslogix-docs/assets/100336275/5f7f1411-775b-4f06-a4fa-7a251cfb0722">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a96dd836-c324-3e58-74de-4fcdedc267bb
* Version Independent ID: a96dd836-c324-3e58-74de-4fcdedc267bb
* Content: [FSLogix Apps RuleEditor and Rule Sets- FSLogix - FSLogix](https://learn.microsoft.com/en-us/fslogix/concepts-fslogix-apps-rule-editor-rule-sets?source=docs)
* Content Source: [fslogix-docs/concepts-fslogix-apps-rule-editor-rule-sets.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/concepts-fslogix-apps-rule-editor-rule-sets.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
This will be fixed in an upcoming doc update
