### ISSUE TITLE
Broken Link in Office Container

### ISSUE THREAD

**Issue by MikelRbrts** [MicrosoftDocs/fslogix-docs#16]
The section 'Office Container' has a broken GitHub link in the second paragraph. 

"[exclude certain data] (configure-office-container-tutorial.md#configure-third-party-exclusions)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 724f8d94-c061-f591-0f64-4fea04b8256d
* Version Independent ID: f896ff2e-90d1-5c9e-b2ce-a3e649fb4990
* Content: [Profile Container vs. Office Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-office-container-cncpt#feedback)
* Content Source: [fslogix-docs/profile-container-office-container-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-office-container-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Links in this document currently appear to be correct, this might have been corrected in an early round of fixes.
