### ISSUE TITLE
Search Roaming Documentation Incorrect

### ISSUE THREAD

**Issue by lettucebuns** [MicrosoftDocs/fslogix-docs#160]
This article states that "FSLogix search roaming functionality is no longer necessary in newer versions of Windows" with the "newer versions of Windows" being "Windows Server 2019 version 1809 and later, Windows 10 and 11 multi-session". This is incorrect. 

1) Windows 10 and 11 are only available in Azure Virtual Desktop (source: [Can I run Windows 10 or Windows 11 Enterprise multi-session outside of the Azure Virtual Desktop service?](https://learn.microsoft.com/en-us/azure/virtual-desktop/windows-10-multisession-faq#can-i-run-windows-10-or-windows-11-enterprise-multi-session-outside-of-the-azure-virtual-desktop-service). This advice only affects those using AVD.

2) If you follow the articles advice and do not configure search roaming for FSLogix OR fail to enable the per-user search catalog registry keys that are outlined as "Applies to Windows 10 (prior to 1809) only" then the search database will not be roamed for your non-AVD workloads. You can recreate this with multiple versions of Windows 10 & 11 including 21H2 and 22H2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 120fcf61-9a2b-a111-9ebd-a8cc37082c34
* Version Independent ID: 120fcf61-9a2b-a111-9ebd-a8cc37082c34
* Content: [Configure Windows Search database roaming - FSLogix](https://learn.microsoft.com/en-us/fslogix/how-to-configure-search-roaming)
* Content Source: [fslogix-docs/how-to-configure-search-roaming.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/how-to-configure-search-roaming.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
I fail to see how this is incorrect.  The footnote specifically calls out Windows 10 and 11 as 'Multi-session' which is NOT to be confused with the Enterprise SKU.

**Comment by lettucebuns** [comment]
Microsofts own support staff is confused about it, so I definitely think clarification is warranted. Nowhere on that page does it say that Windows 10/11 multi-session is Azure only. You can absolutely configure single user search roaming on Windows 10 22H2 despite the article saying "Applies to Windows 10 (prior to 1809) only." - tested and confirmed in our on-premises VMware Horizon deployment.
