### ISSUE TITLE
FSLogix 2.9.8612.60056

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/fslogix-docs#161]
I have deployed the latest AVD image which has FSLogix 2.9.8612.60056. this is not currently listed on the release page. can you provide details on this update please.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Version Independent ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Content: [FSLogix Release Notes - FSLogix](https://learn.microsoft.com/en-us/fslogix/overview-release-notes)
* Content Source: [fslogix-docs/overview-release-notes.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-release-notes.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Apologies, we had some miscommunications with the team who manages the marketplace images.  Look towards Jan 2024 as they will complete on a few items they've needed to fix in their processes.
