### ISSUE TITLE
Typo Correction

### ISSUE THREAD

**Issue by zeeace** [MicrosoftDocs/fslogix-docs#162]
[Enter feedback here]
Option 2 and 3 have a typo at the below sentence marked with asterisk - should be "provider" instead of "provide":
This option incurs extra cost to store the *provide* data in two (2) locations and is a manual event decided by the business stakeholders before a failover is initiated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c8f7f06-6d7b-95c3-5003-ce45192593a7
* Version Independent ID: 1c8f7f06-6d7b-95c3-5003-ce45192593a7
* Content: [Business continuity and disaster recovery options - FSLogix](https://learn.microsoft.com/en-us/fslogix/concepts-container-recovery-business-continuity)
* Content Source: [fslogix-docs/concepts-container-recovery-business-continuity.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/concepts-container-recovery-business-continuity.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Will be fixed in a doc update later today.
