### ISSUE TITLE
FAQ: Can I use object specific settings with Azure AD and cloud-only identities? -> The answer is not clear.

### ISSUE THREAD

**Issue by dweppeler-msft** [MicrosoftDocs/fslogix-docs#163]
Hi,

I think that the answer to this question in FSLogix FAQ is not clear and maybe not correct as it does not work for AADJ VMs with hybrid identities and group object specific settings. The AADJ VMs are not able to get the group SID from AD.

Please update the answer and clarify it.

Thank you,
Daniel
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c12aca1d-7ec9-6d6c-9cc9-db322928328b
* Version Independent ID: c12aca1d-7ec9-6d6c-9cc9-db322928328b
* Content: [FSLogix FAQ - FSLogix](https://learn.microsoft.com/en-us/fslogix/overview-faq#can-i-use-object-specific-settings-with-azure-ad-and-cloud-only-identities)
* Content Source: [fslogix-docs/overview-faq.yml](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-faq.yml)
* Service: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
This will be addressed in a doc update later today.
