### ISSUE TITLE
Publishing date information

### ISSUE THREAD

**Issue by vdebastos** [MicrosoftDocs/fslogix-docs#164]
[Enter feedback here]
After the version number should be the information when it was released.  
For example
**FSLogix 2210 hotfix 2 (2.9.8612.60056)
Date published: September 2023**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Version Independent ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Content: [FSLogix Release Notes - FSLogix](https://learn.microsoft.com/en-us/fslogix/overview-release-notes)
* Content Source: [fslogix-docs/overview-release-notes.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-release-notes.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
The official supportability dates are listed on our Modern Lifecycle page.

https://learn.microsoft.com/en-us/lifecycle/products/fslogix
