### ISSUE TITLE
Exclude HKEY_CURRENT_USER\Software\Microsoft\OneDrive\ from FSLogix profiles.

### ISSUE THREAD

**Issue by PatrickA-RWA** [MicrosoftDocs/fslogix-docs#165]
According to [this MS article ](https://learn.microsoft.com/en-us/sharepoint/sync-vdi-support), "It is not supported to roam the OneDrive registry hive as part of a non-persistent VDI environment." But [this Github post](https://github.com/MicrosoftDocs/fslogix-docs/issues/108) says that excluding registry keys isn't supported. Any suggestions as to how to get around this Catch 22? 

Not sure if this relates to the authentication issues we've been having between O365 apps and OneDrive in Citrix Virtual Apps, but we've looked at everything else we can think of.

**Comment by msft-jasonparker** [comment]
Unfortunately, the FSLogix and OneDrive teams are separate and don't always sync up on docs before they publish.  I'll work with the OneDrive team to create some better alignment.
