### ISSUE TITLE
Another service is required for compacting to occur

### ISSUE THREAD

**Issue by enettekoven** [MicrosoftDocs/fslogix-docs#167]
Next to the defragsvc being set to at least manual for compacting to occur, the service 'Microsoft Storage Spaces SMP' (smphost) also needs to be set to at least manual and not being disabled. If you do disable the smphost service the event 57 will always start with 'Disk was compacted: **false**' in other words, compaction will never occur.

In short: both defragsvc and smphost must be set to at least manual for compaction to occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be1a602a-a4ba-270f-37f9-6a4c0fe84580
* Version Independent ID: be1a602a-a4ba-270f-37f9-6a4c0fe84580
* Content: [Troubleshooting VHD Disk Compaction - FSLogix](https://learn.microsoft.com/en-us/fslogix/troubleshooting-vhd-disk-compaction)
* Content Source: [fslogix-docs/troubleshooting-vhd-disk-compaction.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/troubleshooting-vhd-disk-compaction.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Thanks for the feedback, we'll update the docs.
