### ISSUE TITLE
Request to update "affected versions" on troubleshooting page

### ISSUE THREAD

**Issue by TokenRing** [MicrosoftDocs/fslogix-docs#168]
If the compaction issue listed as "Unexpected VHD disk compaction results" on systems that use mode 3 (with the differencing disk), is still an issue in Hotfix 2 (it is not in the release notes listed [here](https://learn.microsoft.com/en-us/fslogix/overview-release-notes#fslogix-2210-hotfix-2-29861260056)) as well, can this troubleshooting page be updated to reflect that this is an ongoing issue beyond hotfix 1? I think we are being affected by this issue in our environment, and we are on 2210HF2.

My suggestion would be to change the text "Affected version(s): 2210 (2.9.8361.52326), 2210 hotfix 1 (2.9.8440.42104)" to just say "ongoing" or "current release" and then when a new version fixes the issue, then remove the "current release" text. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be1a602a-a4ba-270f-37f9-6a4c0fe84580
* Version Independent ID: be1a602a-a4ba-270f-37f9-6a4c0fe84580
* Content: [Troubleshooting VHD Disk Compaction - FSLogix](https://learn.microsoft.com/en-us/fslogix/troubleshooting-vhd-disk-compaction)
* Content Source: [fslogix-docs/troubleshooting-vhd-disk-compaction.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/troubleshooting-vhd-disk-compaction.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
We will update the text to say 2210 and later
