### ISSUE TITLE
Possible wrong text with option 3. asynchrone should be synchrone

### ISSUE THREAD

**Issue by waltervolkers** [MicrosoftDocs/fslogix-docs#169]
Possible wrong text with option 3. asynchrone should be synchrone

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: 1c8f7f06-6d7b-95c3-5003-ce45192593a7
* Version Independent ID: 1c8f7f06-6d7b-95c3-5003-ce45192593a7
* Content: [Business continuity and disaster recovery options - FSLogix](https://learn.microsoft.com/nl-nl/fslogix/concepts-container-recovery-business-continuity)
* Content Source: [fslogix-docs/concepts-container-recovery-business-continuity.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/concepts-container-recovery-business-continuity.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Async is the correct term used here.
