### ISSUE TITLE
OutlookCachedMode confusing formatting

### ISSUE THREAD

**Issue by DanJermy** [MicrosoftDocs/fslogix-docs#17]
Please note that having details on value 1 for this setting precede value 0 is confusing. This is compounded in that there is no line break after it so it's easy to miss that there *are* details for value 0.
Therefore when attention is drawn to the 'NOTE...' marked in bold, on first (and for me second) glance, it looks like the NOTE applies to value 1, which despite seeming surprising is what we implemented and I only just spotted is likely the cause of outlook performance issues. 
May I suggest that you change the order around and add a line between value 0 and value 1, and ensure that the 'Note' in bold is clearly specific to value 0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6f55cb-b811-c44d-f7bf-3ecc6b84c0b0
* Version Independent ID: 0ce874fa-8b4b-6dc7-92c1-2ad42bcfdd3b
* Content: [Profile Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference#feedback)
* Content Source: [fslogix-docs/profile-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by CyclopsHelpdesk** [comment]
I second this, only spotted because of this comment.

**Comment by DougCoombs** [comment]
reordered value description and added paragraph breaks to improve readability.
