### ISSUE TITLE
Unclear if ACLs should be added or replaced

### ISSUE THREAD

**Issue by realolap** [MicrosoftDocs/fslogix-docs#170]
The documentation shows default ACLs from Azure Files and then lists ACLs to **add**.
But in the later screenshots the defaults are removed and only the new ACLs are shown. 
What is the correct configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef730d-f071-c37f-a868-32a11c4891a8
* Version Independent ID: 28ef730d-f071-c37f-a868-32a11c4891a8
* Content: [Configure SMB Storage Permissions - FSLogix](https://learn.microsoft.com/en-us/fslogix/how-to-configure-storage-permissions)
* Content Source: [fslogix-docs/how-to-configure-storage-permissions.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/how-to-configure-storage-permissions.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by realolap** [comment]
@msft-jasonparker thank you for your response, and yes I see your point about different organisations having different needs for ACLs on files. It would still be good if the docs was clear on what the minimum requirements are for basic scenarios like Azure virtual desktop, backed by Azure Files.
If I remove the default ACLs on the Azure files and only apply creator owner, a login group and an admin group - will that work or will it break some standard functionality of Azure files? 
Reversely if I keep the defaults and only add to them, what RBAC roles or what services are members of, or depending on the default SYSTEM, Users, Administrators and Authenticated Users builtin groups?

**Comment by msft-jasonparker** [comment]
@realolap - I think if you look at the instructions for applying ACLs using Windows explorer we do recommend removing previous inherited permissions.

If you follow our instructions, I can confirm that you will have a successful FSLogix configuration using Azure Files and there is no lost functionality.

I don't see any gaps here.
