### ISSUE TITLE
Teams files are duplicated in AVD

### ISSUE THREAD

**Issue by hvandeursen** [MicrosoftDocs/fslogix-docs#173]
We are encountering a problem that files from teams channels are duplicated after editing in AVD.
The Teams channels are synced via OneDrive to an AVD host equipped with FS logix. OneDrive and FS Logix are the latest versions.
User 1 opens file from explorer \company\filename. As soon as user 2 does this, a file is created with a GUID-like name (many characters). The time of this temporary file is no longer updated. After closing the file, this temporary file is converted to a duplicate with the extension of the AVD host

**Comment by msft-jasonparker** [comment]
Github issues are reserved for issues with our documentation. Please open a support case so we can properly troubleshoot the issue.
