### ISSUE TITLE
Missing Exclusions 

### ISSUE THREAD

**Issue by BrianKitzen** [MicrosoftDocs/fslogix-docs#174]
The Exclusion list on this page does not contain all exclusions: 

Exclude files:
• %ProgramFiles%\FSLogix\Apps\frxdrv.sys
• %ProgramFiles%\FSLogix\Apps\frxdrvvt.sys
• %ProgramFiles%\FSLogix\Apps\frxccd.sys
Exclude processes:
• %ProgramFiles%\FSLogix\Apps\frxccd.exe
• %ProgramFiles%\FSLogix\Apps\frxccds.exe
• %ProgramFiles%\FSLogix\Apps\frxsvc.exe

(see also https://github.com/MicrosoftDocs/architecture-center/issues/2479) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea880afe-8f06-c0e4-1118-ae3286e2f0d0
* Version Independent ID: ea880afe-8f06-c0e4-1118-ae3286e2f0d0
* Content: [Prerequisites for FSLogix - FSLogix](https://learn.microsoft.com/en-us/fslogix/overview-prerequisites#configure-antivirus-file-and-folder-exclusions)
* Content Source: [fslogix-docs/overview-prerequisites.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-prerequisites.md)
* Product: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
Correction. The other article has too many exclusions. The FSLogix product page is the authority of what should or should not be excluded.
