### ISSUE TITLE
Misleading Language on Important Note for FSLogix 2210 Hotfix 3

### ISSUE THREAD

**Issue by jimmyyj** [MicrosoftDocs/fslogix-docs#175]
The "Important" Note for FSLogix 2210 Hotfix 3 contains the following text: This version is only supported on the following operating systems when deployed with new Teams.

This language implies that I **must** have Teams installed in order to use this version.  What about people that are not using Teams?  Should they not use it at all?

Thanks,
Jim

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Version Independent ID: 3c140ca1-20a5-7766-a04d-d1cac53f1466
* Content: [FSLogix Release Notes - FSLogix](https://learn.microsoft.com/en-us/fslogix/overview-release-notes)
* Content Source: [fslogix-docs/overview-release-notes.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview-release-notes.md)
* Service: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
I'll make it more clear

**Comment by msft-jasonparker** [comment]
Fixed
