### ISSUE TITLE
Issue with %sid%

### ISSUE THREAD

**Issue by twistedpro** [MicrosoftDocs/fslogix-docs#176]
I was unable to get this work until I added a G following the %sid%
O:%sid%G:DUD:PAI(A;OICIIO;0x1301bf;;;CO)(A;OICI;FA;;;SY)...........

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef730d-f071-c37f-a868-32a11c4891a8
* Version Independent ID: 28ef730d-f071-c37f-a868-32a11c4891a8
* Content: [Configure SMB Storage Permissions - FSLogix](https://learn.microsoft.com/en-us/fslogix/how-to-configure-storage-permissions)
* Content Source: [fslogix-docs/how-to-configure-storage-permissions.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/how-to-configure-storage-permissions.md)
* Service: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
will update in our next release
