### ISSUE TITLE
New Teams right file format

### ISSUE THREAD

**Issue by Ricasti** [MicrosoftDocs/fslogix-docs#179]
Hi Team,

please double check the file format for the New Teams which is MISX instead of Appx. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15eb1113-886f-a4a2-f59a-5ab16645d884
* Version Independent ID: 15eb1113-886f-a4a2-f59a-5ab16645d884
* Content: [Issues with AppX, MSIX or Microsoft store applications - FSLogix](https://learn.microsoft.com/en-us/fslogix/troubleshooting-appx-issues#when-using-or-switching-to-new-teams-for-vdi-users-report-the-application-is-missing-or-has-long-load-times)
* Content Source: [fslogix-docs/troubleshooting-appx-issues.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/troubleshooting-appx-issues.md)
* Service: **fslogix**
* GitHub Login: @msft-jasonparker
* Microsoft Alias: **japarker**

**Comment by msft-jasonparker** [comment]
AppX and MSIX are interchangable
