### ISSUE TITLE
Cannot Install FSLogix

### ISSUE THREAD

**Issue by orsharon7** [MicrosoftDocs/fslogix-docs#18]
The error is:
"The Security ID may not be assigned as the owner of this object"

I cannot modify security permissions as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb001371-1df6-d412-0de5-3c71047a1774
* Version Independent ID: aa2c6d81-169d-55d3-f8f3-33af9b006448
* Content: [Install FSLogix Agent - FSLogix](https://docs.microsoft.com/en-us/fslogix/install-ht)
* Content Source: [fslogix-docs/install-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/install-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Unclear as to appropriate documentation change to address this item.  No change made.  Please enter another item with specific suggested docs changes.
