### ISSUE TITLE
FSlogix overrides User Setting "Show Hidden files"

### ISSUE THREAD

**Issue by ClientSupportCDB** [MicrosoftDocs/fslogix-docs#180]
Hello everyone,

we are setting up fslogix currently in our test Windows 10 x64 environment and are struggeling with it, because it does override the user choosen Setting "Show Hidden files" in Fileexplorer.
It Should be
"HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -> Hidden -> 1

But after Logoff and after Login it is disabled again. All other Settings are saved corretly. For Example I moved the Taskbar to the left - thats saved. But the Explorer Setting is overritten again.

Is this a bug or a feature i do not understand?
Could not find any information on the internet about this.

Kind regards from Germany

**Comment by msft-jasonparker** [comment]
FSLogix captures the entire user profile including the user's registry hive (ntuser.dat) which includes the setting for preserving File Explorer settings. Appears you may have something else in your environment causing an issue as this has been tested extensively without the ability to reproduce.

You may need to open a support case as outlined here: https://learn.microsoft.com/en-us/fslogix/troubleshooting-fslogix-product-support#open-a-support-request
