### ISSUE TITLE
missing instructions for URL rules

### ISSUE THREAD

**Issue by gonzalre** [MicrosoftDocs/fslogix-docs#20]
Please note that in order to work with Java URL rules, only an XML file is generated and that one must be copied to rules location at C:\Program Files\FSLogix\Apps\Rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751b8c92-4069-14ba-8538-6bcf9dd17906
* Version Independent ID: d743ecee-d322-8c6a-a584-b682a714d704
* Content: [Configure and use Java Version Control - FSLogix](https://docs.microsoft.com/en-us/fslogix/java-version-control-rules-ht#feedback)
* Content Source: [fslogix-docs/java-version-control-rules-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/java-version-control-rules-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Modified Deploying Rule Sets section in order to clarify this.
