### ISSUE TITLE
Windows 10 & Server 2019

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/fslogix-docs#21]
Is it supported to use the same Profile Container for both Windows 10 and Server 2019 OS? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Updated Overview docs to indicate that operating systems that share a profile version should be able to share a profile.
