### ISSUE TITLE
Small typo redirection file

### ISSUE THREAD

**Issue by mcm007** [MicrosoftDocs/fslogix-docs#22]
Hi,

Section name "Structure of redirection.xml file" misspelled redirections.xml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960d3cdb-4c5a-7c10-a78e-127b1216a547
* Version Independent ID: a1bf2ff6-41a6-e840-676e-0eb4b9feed72
* Content: [Profile Container content - FSLogix](https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt#feedback)
* Content Source: [fslogix-docs/manage-profile-content-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/manage-profile-content-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Spelling corrected, thank you!
