### ISSUE TITLE
Is the term 'Profile container' being used intermittently where 'Office container' is the correct term?

### ISSUE THREAD

**Issue by MaranVerweij** [MicrosoftDocs/fslogix-docs#24]
Is the term 'Profile container' being used intermittently where 'Office container' is the correct term? For example:

"Type DWORD
Default Value 0
Data values and use 0: Office Containers disabled. 1: Profile Containers enabled."

It seems to me that both values should read Office Containers. Please verify, I suspect other references incorrectly cite 'Profile Containers' considering this article covers Office Containers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978fd40e-7442-8668-fc98-41fe72488264
* Version Independent ID: 3aaec39c-5ea0-fedc-04ea-e3bd4d7784ff
* Content: [Office Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/office-container-configuration-reference#enabled)
* Content Source: [fslogix-docs/office-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/office-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
This document has been updated.  NOTE: there are times when Profile Container is appropriately referenced.
