### ISSUE TITLE
What kind of function does "FoldersToRemove" have? 

### ISSUE THREAD

**Issue by Edocsyl** [MicrosoftDocs/fslogix-docs#28]
I have a Configuration Registry Entry "FoldersToRemove" REG_MULTI_SZ that contains some paths to "C:\Users\local_[username]". For what is this Registry Entry? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6f55cb-b811-c44d-f7bf-3ecc6b84c0b0
* Version Independent ID: 0ce874fa-8b4b-6dc7-92c1-2ad42bcfdd3b
* Content: [Profile Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference#feedback)
* Content Source: [fslogix-docs/profile-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
This is entered by FSLogix for internal use, not documented.
