### ISSUE TITLE
Azure storage accounts

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/fslogix-docs#29]
The permissions here seem to apply to a Windows file server/share, but not to Azure storage accounts. 

Can you clarify how to achieve this in Azure Storage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d718ea32-d8b7-9771-02eb-ca17ddfac068
* Version Independent ID: 8a030e13-4a6e-d674-1ef2-b6117c207203
* Content: [Storage Permissions for Profile Container and Office Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-storage-config-ht#feedback)
* Content Source: [fslogix-docs/fslogix-storage-config-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-storage-config-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Azure Storage would need to have an SMB share with these or appropriate permissions, no additional documentation is planned.
