### ISSUE TITLE
Profile type is named on the DiffDiskParentFolderPath section but not described

### ISSUE THREAD

**Issue by cmdrr** [MicrosoftDocs/fslogix-docs#30]
"Profile type" is named on the DiffDiskParentFolderPath section but not described on this page, so reader should understand that available values are those on "Profile Container"section, or VHDAccessMode is used instead under Office configuration, or not applying to Office Profile at all.

**Comment by DougCoombs** [comment]
Link to ProfileType docs added in comment.
