### ISSUE TITLE
Easier per-user management

### ISSUE THREAD

**Issue by JamesEdmonds89** [MicrosoftDocs/fslogix-docs#31]
Are there any plans to integrate the per-user management settings into group policy, so we don't have to manually manipulate registry settings?
I'd rather avoid making these reg edits on multiple servers!

**Comment by DougCoombs** [comment]
Please enter an enhancement request through User Voice: https://windowsvirtualdesktop.uservoice.com/forums/921289-fslogix

Closing as this is item as it can not be addressed in docmentation.
