### ISSUE TITLE
Cache Directory is a REG_SZ

### ISSUE THREAD

**Issue by RyanLWilliams** [MicrosoftDocs/fslogix-docs#32]
https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference#cachedirectory

Cache Directory is type REG_SZ not DWORD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e794b36e-21f9-5545-cd15-a528f34cbc46
* Version Independent ID: ec93ddfb-158f-0305-f615-1776086d34c1
* Content: [FSLogix Cloud Cache configuration reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference#cachedirectory)
* Content Source: [fslogix-docs/cloud-cache-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
PR complete, will be live with docs update for 2009, Thanks!
