### ISSUE TITLE
OneNote shows two times with different default values

### ISSUE THREAD

**Issue by iowacountryboy** [MicrosoftDocs/fslogix-docs#33]
OneNote shows a default value of 0 when it appears first on this list just after OneDrive.  It appears in the list again after MicrosoftTeams and shows a default value of 1....which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978fd40e-7442-8668-fc98-41fe72488264
* Version Independent ID: 3aaec39c-5ea0-fedc-04ea-e3bd4d7784ff
* Content: [Office Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/office-container-configuration-reference#feedback)
* Content Source: [fslogix-docs/office-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/office-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, Pull request in, this will be updated on live when 2009 docs update is posted.  Thanks!
