### ISSUE TITLE
inconsistent or unclear 

### ISSUE THREAD

**Issue by rvanderkruk** [MicrosoftDocs/fslogix-docs#34]
First in this article you state: Changes to enhance native search behavior in Windows Server 2019 and Windows 10 multi-session remove the need for FSLogix search functionality.
Then in the table under 'FSLogix provides two mechanisms to roam Search information, Single-user Search and Multi-user Search' is stated:
- Windows 7 and later, Windows Server 2008 R2 and later
- Windows 8 and later, Windows Server 2012 R2 and later

this causes confusion. Should I now make any setting as server 2019 is later than server2008/2012. Please make this rock solid documentation!! 

more coming
Roland van der Kruk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0372ee4-56a3-5b1c-e5df-1d5890c15d3c
* Version Independent ID: b7f96ccb-1bc2-251b-8b7c-4ff20d405b0b
* Content: [Roam the windows search database with Profile Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-search-roaming-ht#feedback)
* Content Source: [fslogix-docs/configure-search-roaming-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-search-roaming-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Notes have been added to the table to explicitly  exclude Windows 10 multi-session and Server 2019 or later.  This will go to the live site with the FSL 2009 docs update.  Thanks!
