### ISSUE TITLE
incorrect sentence

### ISSUE THREAD

**Issue by rvanderkruk** [MicrosoftDocs/fslogix-docs#37]
please rephrase: When configuring Office Container, each Office component is independently included base on settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 724f8d94-c061-f591-0f64-4fea04b8256d
* Version Independent ID: f896ff2e-90d1-5c9e-b2ce-a3e649fb4990
* Content: [Profile Container vs. Office Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-office-container-cncpt)
* Content Source: [fslogix-docs/profile-container-office-container-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-office-container-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
extended the included link to state include data for specific office components and linked to reference for including office components.  Thanks!
