### ISSUE TITLE
Include warning to say excluding parts of the profile should be done with care

### ISSUE THREAD

**Issue by JimMoyle** [MicrosoftDocs/fslogix-docs#38]
People have been using redirections.xml circulated from the internet blindly  this has been causing issues. Add warning something like the following

'Exclusions from the profile may have serious impact on functionality.  Exclusions should be by exception and tested to ensure no loss of functionality is incurred'

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960d3cdb-4c5a-7c10-a78e-127b1216a547
* Version Independent ID: a1bf2ff6-41a6-e840-676e-0eb4b9feed72
* Content: [Profile Container content - FSLogix](https://docs.microsoft.com/en-au/fslogix/manage-profile-content-cncpt)
* Content Source: [fslogix-docs/manage-profile-content-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/manage-profile-content-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Thanks Jim, I will add this!

Doug

**Comment by DougCoombs** [comment]
This pull request is complete, and will be included in the docs update for 2009 docs release.  Thanks!
