### ISSUE TITLE
what if the setting is enabled for both the office and profile containers?

### ISSUE THREAD

**Issue by bitslacker** [MicrosoftDocs/fslogix-docs#39]
Will one be selected over the other if both are configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0372ee4-56a3-5b1c-e5df-1d5890c15d3c
* Version Independent ID: b7f96ccb-1bc2-251b-8b7c-4ff20d405b0b
* Content: [Roam the windows search database with Profile Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-search-roaming-ht#feedback)
* Content Source: [fslogix-docs/configure-search-roaming-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-search-roaming-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
The documentation states that if it is set for both, then the search DB is placed in the profile container.  This has been extended to state that it is recommended that the search DB location is included in EITHER the Office Container or the Profile Container.  This update will be included in the 2009 docs refresh, Thanks!
