### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by camkerr81** [MicrosoftDocs/fslogix-docs#4]
Please provide release notes or link to release notes. FSLogix does not have any currently for this new version released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb001371-1df6-d412-0de5-3c71047a1774
* Version Independent ID: aa2c6d81-169d-55d3-f8f3-33af9b006448
* Content: [Install FSLogix Agent - FSLogix](https://docs.microsoft.com/en-us/fslogix/install-ht)
* Content Source: [fslogix-docs/install-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/install-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by m4trix77** [comment]
Has anyone had issues with this release on Windows 10 1903 where logging in and loading a profile container then blue screens with Group Policy client error access denied then logs user off?

Seems to work with Server 2016 1607 just not W10.

**Comment by m4trix77** [comment]
Has anyone had issues with this release on Windows 10 1903 where logging in and loading a profile container then blue screens with Group Policy client error access denied then logs user off?

Seems to work with Server 2016 1607 just not W10.

**Comment by DougCoombs** [comment]
If this continues to be an issue please open a support ticket at: https://support.fslogix.com/index.php/knowledge-base?view=kb&kbartid=179

**Comment by ceooph** [comment]
Can we updgrade directly previous fslogix legacy version ? Or we must uninstall & install lastest fslogix version ? Thanks Microsoft (& Fslogix) to win money ;-)

**Comment by miked1313** [comment]
@ceooph Yes an in place upgrade appears to install ok and it requires a reboot.

**Comment by DougCoombs** [comment]
Release notes are now available in the FSLogix Forum: https://social.msdn.microsoft.com/Forums/en-us/home?forum=FSLogix
