### ISSUE TITLE
Sample incorrect

### ISSUE THREAD

**Issue by nickde9999** [MicrosoftDocs/fslogix-docs#40]
Samples for Credential Manager do not include the |key| entries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 832b7060-3337-34c5-4d36-5a6818ce143d
* Version Independent ID: 55af0934-f282-1ef9-93d5-d0af268e7e70
* Content: [Configure FSLogix Cloud Cache Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-cloud-cache-tutorial#feedback)
* Content Source: [fslogix-docs/configure-cloud-cache-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-cloud-cache-tutorial.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
|key| appears to be in the documentation, could this be a formatting issue?

**Comment by DougCoombs** [comment]
corrected and extended, Thank you!
