### ISSUE TITLE
OS supportability and Azure storage options

### ISSUE THREAD

**Issue by MrRitt** [MicrosoftDocs/fslogix-docs#41]
Are Windows 7 and 2008 R2 still supported? Or, are they end of life?
Curious if the solution will work with Windows 7 / 2008 R2 accessing the various storage options in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview#requirements)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
As the docs state, FSLogix will work with Windows 7 or later, but in not instance is FSLogix supported in an environment that has been deprecated.  Windows 7 is still supported in certain circumstances, but you would need to verify that you are properly licensed.  This does not require a docs change.
