### ISSUE TITLE
Include & Exclude example

### ISSUE THREAD

**Issue by JGezels** [MicrosoftDocs/fslogix-docs#43]
Seems counter intuitive to show "FolderToDiscard\FolderToKeep" in the include section example or does this mean you can Include a folder in an already excluded folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960d3cdb-4c5a-7c10-a78e-127b1216a547
* Version Independent ID: a1bf2ff6-41a6-e840-676e-0eb4b9feed72
* Content: [Profile Container content - FSLogix](https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt#feedback)
* Content Source: [fslogix-docs/manage-profile-content-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/manage-profile-content-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Your interpretation is correct.  Thanks!@
