### ISSUE TITLE
Structure of redirections.xml file

### ISSUE THREAD

**Issue by wcvanzyl** [MicrosoftDocs/fslogix-docs#44]
It's not clear if VALUE must be defined as something or if it's just part of the schema:
&lt;FrxProfileFolderRedirection ExcludeCommonFolders="&lt;VALUE&gt;"&gt;

If it has to be a value, what would it be and can we have better examples explaining this feature please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960d3cdb-4c5a-7c10-a78e-127b1216a547
* Version Independent ID: a1bf2ff6-41a6-e840-676e-0eb4b9feed72
* Content: [Profile Container content - FSLogix](https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt#feedback)
* Content Source: [fslogix-docs/manage-profile-content-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/manage-profile-content-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by wcvanzyl** [comment]
nevermind - just scrolled to the bottom and it is explained :-)

**Comment by msft-jasonparker** [comment]
This will be addressed in future documentation updates later this month.
