### ISSUE TITLE
RemoveOrphanedOSTFilesOnLogoff setting not working

### ISSUE THREAD

**Issue by alexey-zhel** [MicrosoftDocs/fslogix-docs#45]
RemoveOrphanedOSTFilesOnLogoff setting description is not accurate or feature is not working. I've broken OST file in my lab and got a prompt to create new file after restarting Outlook, but corrupted file has not been deleted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6f55cb-b811-c44d-f7bf-3ecc6b84c0b0
* Version Independent ID: 0ce874fa-8b4b-6dc7-92c1-2ad42bcfdd3b
* Content: [Profile Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference)
* Content Source: [fslogix-docs/profile-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
The default was inaccurately indicated to be on (1).  If you have not explicitly set the setting, please do so.  If you have explicitly set the setting and it failed please follow the support process to find a resolution / enter an item to engineering if needed.
