### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by liquidkristal** [MicrosoftDocs/fslogix-docs#46]
Hi guys.
Attach VHD)x) should be Attach VHD(x) (in the heading on that section and side bar (Assume they are linked though))

Cheers
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b32728-701a-b950-5869-4a14b28c9267
* Version Independent ID: 110001fb-4a39-18cd-53fc-3b4efc3b34ab
* Content: [FSLogix Disk Management Utility Reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/disk-management-utility-reference)
* Content Source: [fslogix-docs/disk-management-utility-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/disk-management-utility-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, Thank you!  this will be live with the 2009 docs update.
