### ISSUE TITLE
Example of using a Credential Manager stored key

### ISSUE THREAD

**Issue by Mriccio** [MicrosoftDocs/fslogix-docs#47]
Would it be possible to provide an example of how the stored fslogix key that was created with frx.exe is entered in the registry key?

ex: (I've cleaned up some of the string to remove some of our info)
type=azure,connectionString="DefaultEndpointsProtocol=https;AccountName=ACCOUNTNAME;AccountKey=|KEY|;EndpointSuffix=ENDPOINTSUFFIX

For the |KEY| I've tried using example(if my saved key is under the entry of ProfileBlob)
AccountName=ProfileBlob  (this didn't work)
AccountName=fslogix/ProfileBlob (this didn't work)
AccountName=|ProfileBlob| (also did not work)
AccountName=|fslogix/ProfileBlob| (this did not work either)

**Comment by DougCoombs** [comment]
The last example |fslogix/ProfileBlob| is the correct syntax.  If the string above is the actual string used, the training " is missing.

Documentation is being updated with a more complete description and example.
