### ISSUE TITLE
Typo in Page Title

### ISSUE THREAD

**Issue by miked1313** [MicrosoftDocs/fslogix-docs#48]
The Page Title (browser tab/window title) has a typo it is "FSLgogix"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210b2987-c214-abe0-d248-8e851b4ba043
* Version Independent ID: 09e4be89-9877-af60-9ab5-a9a4defe11fd
* Content: [FSLgogix installed components and functions - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-installed-components-functions-reference)
* Content Source: [fslogix-docs/fslogix-installed-components-functions-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-installed-components-functions-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, thank you!  This will go live with the docs refresh for 2009 release.
