### ISSUE TITLE
Missing parameter

### ISSUE THREAD

**Issue by wcvanzyl** [MicrosoftDocs/fslogix-docs#49]
The command frx edit-profile=<vhd file that contains profile to be edited> is missing the -filename switch

It should be:
frx edit-profile -filename=

Werner
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f45799-960d-562a-c481-078a0fdda7d6
* Version Independent ID: cda7e89a-1ef8-77f0-d7d2-a602f793a392
* Content: [FSLogix FRX Command-Line Reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/command-line-utility-reference)
* Content Source: [fslogix-docs/command-line-utility-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/command-line-utility-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
corrected, Thanks!
