### ISSUE TITLE
GP client access denied in W10

### ISSUE THREAD

**Issue by m4trix77** [MicrosoftDocs/fslogix-docs#5]
Has anyone had issues with this release on Windows 10 1903 where logging in and loading a profile container then blue screens with Group Policy client error access denied then logs user off?

Seems to work with Server 2016 1607 just not W10.

**Comment by DougCoombs** [comment]
Thanks for your comment.  If this issue continues, please create a support incident here: https://support.fslogix.com/index.php/knowledge-base?view=kb&kbartid=179

Also, for non-documentation items please feel free to use the technical forum at: https://social.msdn.microsoft.com/Forums/en-us/home?forum=FSLogix.
