### ISSUE TITLE
Missing status code 0x00000064

### ISSUE THREAD

**Issue by cybershadow1** [MicrosoftDocs/fslogix-docs#50]
Missing status code 0x00000064

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ddcd3b5-8767-395d-47f1-d411d699da9c
* Version Independent ID: b1449d8b-86ee-48dd-ac30-44a15041af1b
* Content: [FSLogix error code reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-error-codes-reference)
* Content Source: [fslogix-docs/fslogix-error-codes-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-error-codes-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Logfiles are being updated with extended information on resolution and error details.
