### ISSUE TITLE
Missing WriteCacheDirectory option

### ISSUE THREAD

**Issue by brbish** [MicrosoftDocs/fslogix-docs#51]
The WriteCacheDirectory is list in the GPO so it should probably have an entry here.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e794b36e-21f9-5545-cd15-a528f34cbc46
* Version Independent ID: ec93ddfb-158f-0305-f615-1776086d34c1
* Content: [FSLogix Cloud Cache configuration reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference)
* Content Source: [fslogix-docs/cloud-cache-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
This info was added
