### ISSUE TITLE
FSLogix Cache Directory reg type error

### ISSUE THREAD

**Issue by jongalac** [MicrosoftDocs/fslogix-docs#53]
Guys, the FSLogix cache directory is listed as a DWORD in this document when its a string value - it should be REG_SZ, please amend, cheers 
John Gallacher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e794b36e-21f9-5545-cd15-a528f34cbc46
* Version Independent ID: ec93ddfb-158f-0305-f615-1776086d34c1
* Content: [FSLogix Cloud Cache configuration reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference)
* Content Source: [fslogix-docs/cloud-cache-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, Thank you!

**Comment by jongalac** [comment]
Awesome cheers!
