### ISSUE TITLE
Registry path for determining MultiSessionMachine is not correctly documented

### ISSUE THREAD

**Issue by mekroebo** [MicrosoftDocs/fslogix-docs#55]
Minor thing, but the registry key for determining if the machine is a multi session machine should be:

_HKLM\System\CurrentControlSet\Control\Terminal Server\fSingleSessionPerUser_ (Note the space between _Terminal_ and _Server_. Took me quite some time to spot that :) )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5945f8f-44c8-f087-9242-a33e3b1314db
* Version Independent ID: 96ff0876-4761-7f23-8916-b16b2226b921
* Content: [Supporting concurrent connections and multiple connections with Profile Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht)
* Content Source: [fslogix-docs/configure-concurrent-multiple-connections-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-concurrent-multiple-connections-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, Thank you!
