### ISSUE TITLE
Where is the location of the Local Cache when using CloudCache?

### ISSUE THREAD

**Issue by tonycaidotcom** [MicrosoftDocs/fslogix-docs#56]
Where is the location of the Local Cache when using CloudCache?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef9db9f-d2a5-e4be-57cc-265310659c02
* Version Independent ID: baa86801-4ace-567b-a0e7-6d4ea072df5f
* Content: [Cloud Cache for resiliency and availability - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-resiliency-availability-cncpt)
* Content Source: [fslogix-docs/cloud-cache-resiliency-availability-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-resiliency-availability-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
This is documented in cloud cache configuration reference and is based on CacheDirectory setting with a default of c:\ProgramData\FSLogix\Cache
