### ISSUE TITLE
Missing "\"

### ISSUE THREAD

**Issue by JasonRBeer** [MicrosoftDocs/fslogix-docs#59]
It doesn't look like you can make pull requests for fslogix-docs like you can with other Microsoft documentation. Anyway, the following lines should be changed:

WRONG
Copy the ADMX file (fslogix.admx) to %logonserver%\sysvol%userdnsdomain%\policies\PolicyDefinitions
Copy the ADML file (fslogix.adml) to %logonserver%\sysvol%userdnsdomain%\policies\PolicyDefinitions\en-US

RIGHT
Copy the ADMX file (fslogix.admx) to %logonserver%\sysvol\%userdnsdomain%\policies\PolicyDefinitions
Copy the ADML file (fslogix.adml) to %logonserver%\sysvol\%userdnsdomain%\policies\PolicyDefinitions\en-US

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a490a35-0b6c-c2e5-dc10-5f72c7e906b7
* Version Independent ID: bca503d7-f9a6-6e95-7fa9-f5d46b8ac801
* Content: [Use FSLogix Group Policy Template Files - FSLogix](https://docs.microsoft.com/en-us/fslogix/use-group-policy-templates-ht?source=docs)
* Content Source: [fslogix-docs/use-group-policy-templates-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/use-group-policy-templates-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by JasonRBeer** [comment]
It looks like I did the same thing as the author :). 

RIGHT
Copy the ADMX file (fslogix.admx) to %logonserver%\sysvol\\%userdnsdomain%\policies\PolicyDefinitions
Copy the ADML file (fslogix.adml) to %logonserver%\sysvol\\%userdnsdomain%\policies\PolicyDefinitions\en-US

**Comment by DougCoombs** [comment]
Syntax error in mockup, corrected, thank you for the heads up!
