### ISSUE TITLE
Typo on a line ..."sing in and sign out"...

### ISSUE THREAD

**Issue by Goadstir** [MicrosoftDocs/fslogix-docs#6]
Section: Key Capabilities - https://docs.microsoft.com/en-us/fslogix/overview#key-capabilities

The typo line: "profiles can often be large, &lt;sing&gt; in and sign out times"

Should Read: "profiles can often be large, sign in and sign out times"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview#key-capabilities)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by dsindona** [comment]
Thanks for noting, this is now fixed.
