### ISSUE TITLE
Replace "frx.exe" by "frx" in frx commands

### ISSUE THREAD

**Issue by GitVali** [MicrosoftDocs/fslogix-docs#60]
In the "Protect Azure Key with Credential Manager" section, there is a list of commands available. The syntax doesn't look good, I had to use "frx" instead of "frx.exe" to make it work.
For instance, using "frx.exe add-secure-key" returns "Operation completed successfully!" but nothing happens and the key is not created whereas using "frx add-secure-key" returns "Secure key added successfully" and the key is actually added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 832b7060-3337-34c5-4d36-5a6818ce143d
* Version Independent ID: 55af0934-f282-1ef9-93d5-d0af268e7e70
* Content: [Configure FSLogix Cloud Cache Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-cloud-cache-tutorial#protect-azure-key-with-credential-manager)
* Content Source: [fslogix-docs/configure-cloud-cache-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-cloud-cache-tutorial.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
tested, frx.exe worked correctly with syntax as in docs.  If the issue persists perhaps open a support ticket?
