### ISSUE TITLE
Incorrect details around Cache Locations

### ISSUE THREAD

**Issue by JamesKindon** [MicrosoftDocs/fslogix-docs#61]
There are some incorrect values in this page

The CacheDirectory key is actually a **string value** not a DWORD

The CacheDirectory key is located in the HKLM\SYSTEM\CurrentControlSet\Services\frxccd\Parameters key not HKLM\SYSTEM\CurrentControlSet\Services\frxccds\Parameters key

The Default values for these keys I think should be the C:\ProgramData\FSLogix\ directory with the relevant folder for the relevant path

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e794b36e-21f9-5545-cd15-a528f34cbc46
* Version Independent ID: ec93ddfb-158f-0305-f615-1776086d34c1
* Content: [FSLogix Cloud Cache configuration reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference)
* Content Source: [fslogix-docs/cloud-cache-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected DWORD issue.  NOTE: both frxccd and frxccds are used for different values, please see note.  Thanks!
