### ISSUE TITLE
Exclusion file is not located here

### ISSUE THREAD

**Issue by drksilenc** [MicrosoftDocs/fslogix-docs#62]
I am using fslogix 2.9.7349.30108 and there is no redirections.xml located at the location in your article. you should include a default xml file in your document. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960d3cdb-4c5a-7c10-a78e-127b1216a547
* Version Independent ID: a1bf2ff6-41a6-e840-676e-0eb4b9feed72
* Content: [Profile Container content - FSLogix](https://docs.microsoft.com/en-us/fslogix/manage-profile-content-cncpt)
* Content Source: [fslogix-docs/manage-profile-content-cncpt.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/manage-profile-content-cncpt.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
This is addressed in a future documentation update coming later this month.
