### ISSUE TITLE
'SIDDirNameMatch' has the wrong description.

### ISSUE THREAD

**Issue by rtebrake** [MicrosoftDocs/fslogix-docs#64]
SIDDirNameMatch and SIDDirNamePattern have the same description ("_Specifies a string pattern used when creating a SID container folder_").

Instead, SIDDirNameMatch should have a description similar to VHDNameMatch ("_Specifies a string pattern used to match (find) the profile VHD(X) file_.")
This applies to both the Profile container and Office container registry reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978fd40e-7442-8668-fc98-41fe72488264
* Version Independent ID: 3aaec39c-5ea0-fedc-04ea-e3bd4d7784ff
* Content: [Office Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/office-container-configuration-reference)
* Content Source: [fslogix-docs/office-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/office-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Corrected, Thank you!
