### ISSUE TITLE
Fslogix registry keys page missing CleanOutNotifications 

### ISSUE THREAD

**Issue by jputseys** [MicrosoftDocs/fslogix-docs#67]
Log files are listing a specific registry key that isn't documented. 

Setting this key solves the issue we're having, but it's not documented so we're not sure what the full effect of this is.

We don't seem to be the only one, see this post from another user:
https://social.msdn.microsoft.com/Forums/en-US/0fcc7614-75f3-4da7-a770-af9eebeb0bb0/softwarefslogixprofilescleanoutnotifications-documentation-missing?forum=FSLogix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6f55cb-b811-c44d-f7bf-3ecc6b84c0b0
* Version Independent ID: 0ce874fa-8b4b-6dc7-92c1-2ad42bcfdd3b
* Content: [Profile Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference)
* Content Source: [fslogix-docs/profile-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
Added the configuration - changes should be live in 24 hrs
