### ISSUE TITLE
Typo in SizeinMBs value description

### ISSUE THREAD

**Issue by rtebrake** [MicrosoftDocs/fslogix-docs#69]
The SizeinMBs description contains the following sentence: "Default of 3000 = 30 GB". There is a zero missing, this should be 'Default of 30000 = 30 GB'.

Note that it's correct on the Profile container page,the above is only present in the Office Container reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978fd40e-7442-8668-fc98-41fe72488264
* Version Independent ID: 3aaec39c-5ea0-fedc-04ea-e3bd4d7784ff
* Content: [Office Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/office-container-configuration-reference)
* Content Source: [fslogix-docs/office-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/office-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
This has been fixed. Thank you.
