### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/fslogix-docs#7]
Can we get the release notes for the most recent releases added to this documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview#feedback)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by DougCoombs** [comment]
Release notes are now available in the FSLogix Forum: https://social.msdn.microsoft.com/Forums/en-us/home?forum=FSLogix
