### ISSUE TITLE
Concurrent/Multiple well covered - what about single connection?

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/fslogix-docs#70]
I could not locate specific recommendation when only using single connection by user (multiple users will connect to same environment, but each user is limited to 1 session only).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5945f8f-44c8-f087-9242-a33e3b1314db
* Version Independent ID: 96ff0876-4761-7f23-8916-b16b2226b921
* Content: [Supporting concurrent connections and multiple connections with Profile Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht)
* Content Source: [fslogix-docs/configure-concurrent-multiple-connections-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-concurrent-multiple-connections-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
This is the default configuration and it is assumed unless otherwise configured.
