### ISSUE TITLE
Reason Code 6 missing from documentation

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/fslogix-docs#74]
I am getting "Reason = 0x00000006", but 6 appears to be missing on this page under "Reason Code" section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ddcd3b5-8767-395d-47f1-d411d699da9c
* Version Independent ID: b1449d8b-86ee-48dd-ac30-44a15041af1b
* Content: [FSLogix error code reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-error-codes-reference)
* Content Source: [fslogix-docs/fslogix-error-codes-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-error-codes-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
Updated all the codes - changes will go live by EOD
