### ISSUE TITLE
Tutorial loops

### ISSUE THREAD

**Issue by Ferretaa** [MicrosoftDocs/fslogix-docs#76]
The next step loops back to "Configure Profile Container to redirect User Profiles" which is the start of the tutorial. 
This seems illogical. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4602cd0-2a1d-0a8f-6bf6-66ca0bdb3bdf
* Version Independent ID: 8c66f1fa-1b67-3212-abd9-54e632f2b83f
* Content: [Implement Application Masking Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/implement-application-masking-tutorial)
* Content Source: [fslogix-docs/implement-application-masking-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/implement-application-masking-tutorial.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
Removed next steps section
