### ISSUE TITLE
Document can't find on the left tap

### ISSUE THREAD

**Issue by captain9521** [MicrosoftDocs/fslogix-docs#77]
[Enter feedback here]
I entered this doc by google but there is not on the left side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a490a35-0b6c-c2e5-dc10-5f72c7e906b7
* Version Independent ID: bca503d7-f9a6-6e95-7fa9-f5d46b8ac801
* Content: [Use FSLogix Group Policy Template Files - FSLogix](https://docs.microsoft.com/en-us/fslogix/use-group-policy-templates-ht)
* Content Source: [fslogix-docs/use-group-policy-templates-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/use-group-policy-templates-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
this has been fixed - changes go live EOD
