### ISSUE TITLE
frxrobobopy needs its UI strings

### ISSUE THREAD

**Issue by lordjeb** [MicrosoftDocs/fslogix-docs#78]
RE: frxrobocopy

In addition to copying C:\Windows\system32\robocopy.exe to C:\Program Files\FSLogix\Apps\frxrobocopy.exe, we should note that the UI for robocopy also requires that C:\Windows\system32\en-US\robocopy.exe.mui to be copied to C:\Program Files\FSLogix\Apps\en-US\frxrobocopy.exe.mui. Without doing this, the UI for robocopy cannot display strings, and any robocopy logging done via RobocopyLogPath setting will be illegible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210b2987-c214-abe0-d248-8e851b4ba043
* Version Independent ID: 09e4be89-9877-af60-9ab5-a9a4defe11fd
* Content: [FSLogix installed components and functions - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-installed-components-functions-reference)
* Content Source: [fslogix-docs/fslogix-installed-components-functions-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-installed-components-functions-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
Under consideration ;)
