### ISSUE TITLE
Update product name

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/fslogix-docs#84]
In the Requirements section, change product name from Microsoft 365 Business to Microsoft 365 Business Premium.
https://www.microsoft.com/en-us/us-partner-blog/2020/04/08/microsoft-365-new-name-same-price-same-great-value/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview?source=docs)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
Business is the accurate name as it includes Basic, Standard and Premium

**Comment by mprentice22153** [comment]
But the only product that includes FSLogix, and is permitted to work within Citrix/RDS environments, is the Business Premium product thus the need to update the name to accurately reflect the product.
