### ISSUE TITLE
ConcurrentUserSessions setting should be removed

### ISSUE THREAD

**Issue by lordjeb** [MicrosoftDocs/fslogix-docs#85]
This configuration setting has been removed from the product, and we are relying on Windows settings that control whether or not a user can logon to the machine twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6f55cb-b811-c44d-f7bf-3ecc6b84c0b0
* Version Independent ID: 0ce874fa-8b4b-6dc7-92c1-2ad42bcfdd3b
* Content: [Profile Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference)
* Content Source: [fslogix-docs/profile-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by lintFan** [comment]
It was removed in the FSLogix 2009 release, so you might want to leave it in with a note that it only applies to previous versions.

**Comment by MikeStreetz** [comment]
Under what scenario do you see multiple sessions from the same user on the same server?
The default settings for RDP for server OS limits users to a single session. You've mentioned overriding this setting, but not why anyone would ever need to. 
It's mentioned that this is common in citrix environments, but so is session sharing. 

I'm trying to understand the scenario that the concurrent connections setting is trying to solve for. Most people misinterpret this setting as being *required* in RDSH environments, so clarification around this would really help.  
I also note that it's gone entirely in newer versions. 
What did it ever do, if anything?

**Comment by lordjeb** [comment]
@MikeStreetz since the settings removal, FSLogix just follows the behavior of the OS, if the setting (fSingleSessionPerUser) is enabled there. So a separate setting in FSLogix is not required.

The only concrete case I have seen is an environment where multiple users wanted to use the same account to login to a server, but each have their own desktop session. This still leaves me wondering WHY somebody wants that, but... who can understand the human heart? ;)

**Comment by MikeStreetz** [comment]
Ha! There's a use case I had not thought of but could definitely see requiring this. 
Thanks for clearing up how it works now.

**Comment by davisray1983** [comment]
Based on what I am reading then. FSLogix was doing the same things that MS (fSingleSessionPerUser) and Citrix ( Session sharing is doing). Which would make sense why they took it off now because it's now following the OS. 
Which are this key and it enabled by default

Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server
fSingleSessionPerUser = DWORD 1 is set by default.

**Comment by davisray1983** [comment]
Which then I can assume Citrix Session sharing will do the same thing in place now as well at the Citrix Level.

**Comment by davisray1983** [comment]
Does anyone know how to get the documentation updated to reflect pulling it out and relying on the Windows OS now, as mentioned above? I believe it may be causing some confusion are the term in the doc around "Citrix Implementation" 

https://docs.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht#concurrent-connections-with-profile-container-and-office-container

1. fSingleSessionPerUser  is applied to RDSH, not Citrix Virtual App (XenApp after 7.6) https://support.citrix.com/article/CTX203046

2. Session sharing would be used here in the Citrix Stack, which allows the same user to open multiple sessions under the same ID for application on that server. All applications launch in the same application session
“Session sharing is the ability of a seamless published application to be executed over the same connection as other seamless applications that are already running on the same server, under an existing Session ID of a user.”

**Comment by SteveD-MSFT** [comment]
Thanks for calling this out. This has been removed from our documentation and the change will be published with our next public preview - available this month.

**Comment by davisray1983** [comment]
Thank you .

**Comment by davisray1983** [comment]
Thank you

**Comment by bradmoutoux** [comment]
So can you tell me WHY it was removed?  What is the control for this that replaces that???  I CANNOT log into any of my servers except ONE AT A TIME because I run into the profile container cannot be opened due to it being open on another server.  Makes it very difficult to manage more than one Session Host.  So if you haven't noticed there is, in fact, and use case for this.  I think you would have thought a little harder before removing this setting.

**Comment by lordjeb** [comment]
@bradmoutoux Check out the documentation page https://learn.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht for more info. The ConcurrentUserSettings setting is not for single user access from multiple session hosts. Rather, it is for multiple sessions on a single host. Since this requires a Windows setting to be enabled, FSLogix was made to just follow the Windows setting. If it's on for Windows, it's on for FSLogix.

For access from multiple machines, what you want is the ProfileType setting for Profiles feature and the VHDAccessMode setting for the ODFC feature.

**Comment by bradmoutoux** [comment]
Thanks.  VHDAccessMode did it for me. 😊

Sincerely,

Brad Moutoux
Systems Administrator
1045 S John Rodes Blvd | Melbourne, FL 32904
Office: 321-473-0327 | Mobile: 321-438-5447
www.cmsnextech.com<http://www.cmsnextech.com/>
***@***.***
Click Here<https://www.cmsnextech.com/wp-content/uploads/2022/08/Self-Performing-State-Map-8222-1.pdf> to see our self-performing area.
