### ISSUE TITLE
Configuring for local system account

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/fslogix-docs#87]
To everyone struggeling with application masking (exception) for local system account: when configuring in the gui "NT AUTHORITY\SYSTEM" is automatically added as a group (even though I chose to add a user). The .fxa file will contain the line
0x00000012	S-1-5-18		NT AUTHORITY\SYSTEM	0	0
for an excpection to system. But the exception ("not apply") will not work like this.
Only when changing the first item to
0x00000006
did the exception work. If you wish to apply (instead of "not appply") a rule to system. Switch from 0x00000011 to 0x00000005.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abbd66f3-5e06-8f21-3545-7c71a72400b4
* Version Independent ID: c3ea68be-b26d-7e9b-61d2-c4c3c62e4232
* Content: [Application Masking users and groups - FSLogix](https://docs.microsoft.com/en-us/fslogix/application-masking-users-groups-ht)
* Content Source: [fslogix-docs/application-masking-users-groups-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/application-masking-users-groups-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by ld0614** [comment]
@jasminrueegger THANK YOU!  I was running round in circles on this for hours 😢
