### ISSUE TITLE
Typo in Command section

### ISSUE THREAD

**Issue by bugman168** [MicrosoftDocs/fslogix-docs#88]
There is a typo in the documentation in the Example box of the following command:

Enable Shell Refresh Notification
Command
enable-shnot

Example
frx enable-schnot 
should be : enable-shnot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77f45799-960d-562a-c481-078a0fdda7d6
* Version Independent ID: cda7e89a-1ef8-77f0-d7d2-a602f793a392
* Content: [FSLogix FRX Command-Line Reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/command-line-utility-reference#feedback)
* Content Source: [fslogix-docs/command-line-utility-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/command-line-utility-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by SteveD-MSFT** [comment]
Fixed and scheduled to be published.
