### ISSUE TITLE
Included folders (redirections.xml) get created incorrectly in the container

### ISSUE THREAD

**Issue by luprc** [MicrosoftDocs/fslogix-docs#89]
Scenario with redirections.xml (excerpt):

`<Excludes>`
`  <Exclude Copy="0">Documents</Exclude>`
`</Excludes>`

`<Includes>`
`  <Include>Documents\SomeFolderNotToExclude</Include>`
`</Includes>`

With a new Profile container being created, the folder "Documents\SomeFolderNotToExclude" does not exist yet. It is created in the container, however not as a folder but **as a file**. As a result, it is not accessible from the filesystem, getting a Windows error message box "Folder name incorrect".

Our FSLogix version installed: FSLogix_Apps_2.9.7621.30127

**Comment by msft-jasonparker** [comment]
This is addressed in a future documentation update coming later this month.
