### ISSUE TITLE
Missing reason code

### ISSUE THREAD

**Issue by cwidhelm** [MicrosoftDocs/fslogix-docs#90]
The page is missing a reason code of 5.

Reason: 0x00000005, Message: Reason initialized to empty state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ddcd3b5-8767-395d-47f1-d411d699da9c
* Version Independent ID: b1449d8b-86ee-48dd-ac30-44a15041af1b
* Content: [FSLogix error code reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/fslogix-error-codes-reference)
* Content Source: [fslogix-docs/fslogix-error-codes-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/fslogix-error-codes-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by MyNameIsRatchet** [comment]
Any chance we'll know the reason for this error or maybe somehow a fix for it?
It's very frustrating.

**Comment by nyhmbo** [comment]
We are seeing this error every day from a handful of users. how come this is not documented anywhere

**Comment by TheVessel** [comment]
I need to know an answer to this as well or at least how to fix the problem. I restarted the session host Domain Controller and The RDP server still have this error.

**Comment by msft-jasonparker** [comment]
Error codes updated
