### ISSUE TITLE
VolumeType default value vhd instead of "vhd"

### ISSUE THREAD

**Issue by RobVyK** [MicrosoftDocs/fslogix-docs#91]
The current documentation shows the default value for VolumeType being "vhd", while the correct value should be without the quotation marks.
This causes some confusion as customers set the value to "vhd" instead of **vhd**
The FSLogix agent detects the incorrect value and defaults back to using the correct vhd , but it would be good to update the public documentation to reflect the correct value from the start.

Example from the FSLogix Support Tool:
[09:24:30.469][tid:00000e60.000067d8][INFO]             Configuration Read (REG_SZ): SOFTWARE\FSLogix\Profiles\VolumeType.  Data: "vhd"
[09:24:30.469][tid:00000e60.000067d8][WARN: 00000000]   VolumeType = '"vhd"' invalid configuration (must be set to 'vhd' or 'vhdx') Defaulting to: vhd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6f55cb-b811-c44d-f7bf-3ecc6b84c0b0
* Version Independent ID: 0ce874fa-8b4b-6dc7-92c1-2ad42bcfdd3b
* Content: [Profile Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference#volumetype)
* Content Source: [fslogix-docs/profile-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
fixed - changes go live EOD
