### ISSUE TITLE
User Voice link does not work anymore

### ISSUE THREAD

**Issue by CharlesNRU** [MicrosoftDocs/fslogix-docs#92]
User Voice site for FSLogix is down. Can you remove link and/or provide an alternative to propose enhancements to FSLogix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c190dc-ff1f-24c0-201a-fb8a741aaaa4
* Version Independent ID: 5e7268b8-88d9-cbdd-d733-220ac08d3d3e
* Content: [FSLogix Overview - FSLogix](https://docs.microsoft.com/en-us/fslogix/overview)
* Content Source: [fslogix-docs/overview.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/overview.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by SteveD-MSFT** [comment]
Thanks for the feedback. This will be fixed in the upcoming documentation update.
