### ISSUE TITLE
Copy/paste error

### ISSUE THREAD

**Issue by JelleGraaf** [MicrosoftDocs/fslogix-docs#93]
On this page, there's a copied piece of text, which should have been altered for its new location. There's two purple "Note" fields. They both say the same. The second one (under "Mode 2 (local)") should start with "Mode 2 (Local)", instead of "Mode 2 (Network)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5945f8f-44c8-f087-9242-a33e3b1314db
* Version Independent ID: 96ff0876-4761-7f23-8916-b16b2226b921
* Content: [Supporting concurrent connections and multiple connections with Profile Container - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-concurrent-multiple-connections-ht)
* Content Source: [fslogix-docs/configure-concurrent-multiple-connections-ht.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-concurrent-multiple-connections-ht.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by msft-jasonparker** [comment]
the page was updated
