### ISSUE TITLE
Insure vs Ensure

### ISSUE THREAD

**Issue by edlaguni** [MicrosoftDocs/fslogix-docs#94]
1: Only when the Profile Container is attached, the Outlook setting that enables cached mode will temporarily be set until the container is detached. This setting **insures** cached mode is used only when the container is attached.

NOTE: Outlook must be configured for online mode for this feature to work. This **insures** if FSLogix gets disabled, that large OST files won't be downloaded. HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\office\16.0\Outlook\OST\NoOST:DWORD = 2

I don't think "insure" is the right term here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6f55cb-b811-c44d-f7bf-3ecc6b84c0b0
* Version Independent ID: 0ce874fa-8b4b-6dc7-92c1-2ad42bcfdd3b
* Content: [Profile Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference)
* Content Source: [fslogix-docs/profile-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/profile-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by SteveD-MSFT** [comment]
Good catch. Updated.
