### ISSUE TITLE
Update Profile Containers to Office Containers on the description for the Office Containers registry key

### ISSUE THREAD

**Issue by woolardn** [MicrosoftDocs/fslogix-docs#98]
Page:
https://docs.microsoft.com/en-us/fslogix/configure-office-container-tutorial

Section:
Configure Office Container Registry settings

Typo:
Enabled (required setting) | DWORD | 1 | 0: **Profile Containers** disabled. 1: **Profile Containers** enabled

Should be updated to:
Enabled (required setting) | DWORD | 1 | 0: **Office Containers** disabled. 1: **Office Containers** enabled

Reason:
This registry key on this page is pointing to where you would enable Office Containers, not Profile Containers.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2abb4dc-ab6a-16ef-5f4c-75e841c7aa74
* Version Independent ID: 1a4ce9f8-89c0-db9e-a08d-9e63f40766c3
* Content: [Configure Office Container Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-office-container-tutorial)
* Content Source: [fslogix-docs/configure-office-container-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-office-container-tutorial.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
updated - changes go live at the EOD
