### ISSUE TITLE
Registry key value in Screenshot needs an update

### ISSUE THREAD

**Issue by ankulbhardwaj** [MicrosoftDocs/fslogix-docs#99]
The attached screenshot which talks about configuring Registry key "Enabled" should have a value of 1. I have highlighted
![changevalue](https://user-images.githubusercontent.com/86134788/126885867-2604c7e8-5600-4237-b796-6c64f1d3a4f8.PNG)
 the same in the screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 734788a0-bfe6-1916-7300-1fea39127604
* Version Independent ID: 254293a7-3f94-d1b8-50f4-4eda0f20552d
* Content: [Configure Profile Container Tutorial - FSLogix](https://docs.microsoft.com/en-us/fslogix/configure-profile-container-tutorial?WT.mc_id=modinfra-17152-thmaure)
* Content Source: [fslogix-docs/configure-profile-container-tutorial.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/configure-profile-container-tutorial.md)
* Product: **fslogix**
* GitHub Login: @SteveD-MSFT
* Microsoft Alias: **stdowns**

**Comment by msft-jasonparker** [comment]
The screenshot does not recommend what the value should be only where the keys exist and what they are called.
